/*==============================================================================*/
/**
 *
 * Copyright (C) iSOFT   (2023)
 *
 * All rights reserved.
 *
 * This document contains proprietary information belonging to iSOFT.
 * Passing on and copying of this document, and communication
 * of its contents is not permitted without prior written authorization.
 * 
 ********************************************************************************
 * 
 *  @MCU                : R7F7015833
 *  @file               : PduR_PBcfg.h
 *  @author             : iSoft
 *  @date               : 2026-01-22 11:44:20
 *  @vendor             : iSoft
 *  @description        : 
 *  @specification(S)   : AUTOSAR Classic Platform R19-11
 *  @toolVersion        : 2.2.0.3
 */
/*==============================================================================*/

#ifndef  PDUR_PBCFG_H
#define  PDUR_PBCFG_H

/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/

/*******************************************************************************
**                      Version Information                                   **
*******************************************************************************/
#define PDUR_CFG_H_AR_RELEASE_MAJOR_VERSION    4u
#define PDUR_CFG_H_AR_RELEASE_MINOR_VERSION    5u
#define PDUR_CFG_H_AR_RELEASE_REVISION_VERSION 0u
#define PDUR_CFG_H_SW_MAJOR_VERSION            2u
#define PDUR_CFG_H_SW_MINOR_VERSION            3u
#define PDUR_CFG_H_SW_PATCH_VERSION            1u

/*******************************************************************************
**                      Macros                                                **
*******************************************************************************/
#define PDUR_SRC_PDU_SUM           173u

#define PDUR_SRCPDU_COM_DIAG_DTCInfo_IAM_CONTROLLER_0_IAM_Tx          0u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP60_CONTROLLER_0_IAM_Tx          1u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP61_CONTROLLER_0_IAM_Tx          2u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP62_CONTROLLER_0_IAM_Tx          3u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP63_CONTROLLER_0_IAM_Tx          4u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP64_CONTROLLER_0_IAM_Tx          5u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP65_CONTROLLER_0_IAM_Tx          6u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP66_CONTROLLER_0_IAM_Tx          7u
#define PDUR_SRCPDU_COM_IAM_CONNCAN_100ms_FrP18_CONTROLLER_0_IAM_Tx          8u
#define PDUR_SRCPDU_COM_IAM_CONNCAN_200ms_FrP01_CONTROLLER_0_IAM_Tx          9u
#define PDUR_SRCPDU_COM_IAM_CONNCAN_200ms_FrP02_CONTROLLER_0_IAM_Tx          10u
#define PDUR_SRCPDU_COM_IAM_CONNCAN_Event_FrS20_CONTROLLER_0_IAM_Tx          11u
#define PDUR_SRCPDU_COM_IAM_CONNCAN_Event_FrS21_CONTROLLER_0_IAM_Tx          12u
#define PDUR_SRCPDU_COM_IAM_CONNCANFD_100ms_FrP19_CONTROLLER_0_IAM_Tx          13u
#define PDUR_SRCPDU_COM_IAM_CONNCANFD_Event_FrS04_CONTROLLER_0_IAM_Tx          14u
#define PDUR_SRCPDU_COM_IAM_CONNCANFD_Event_FrS42_CONTROLLER_0_IAM_Tx          15u
#define PDUR_SRCPDU_COM_IAM_CONNCANFD_Event_FrS43_CONTROLLER_0_IAM_Tx          16u
#define PDUR_SRCPDU_COM_IAM_CONNCANFD_Event_FrS44_CONTROLLER_0_IAM_Tx          17u
#define PDUR_SRCPDU_COM_IAM_CONNCANFD_EvtInfo_CONTROLLER_0_IAM_Tx          18u
#define PDUR_SRCPDU_COM_IAM_SecOC_ComKeyResp_CONTROLLER_0_IAM_Tx          19u
#define PDUR_SRCPDU_COM_IAM_SecOC_Log_CONTROLLER_0_IAM_Tx          20u
#define PDUR_SRCPDU_COM_IAM_ZONE_CONNCANFD_100ms_FrP56_CONTROLLER_0_IAM_Tx          21u
#define PDUR_SRCPDU_COM_TBOX_CONNCAN_20ms_FrP02_CONTROLLER_0_IAM_Tx          22u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP49_CONTROLLER_0_IAM_Tx          23u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP55_CONTROLLER_0_IAM_Tx          24u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP58_CONTROLLER_0_IAM_Tx          25u
#define PDUR_SRCPDU_COM_IAM_BKPCANFD_1000ms_FrP59_CONTROLLER_0_IAM_Tx          26u
#define PDUR_SRCPDU_COM_synthesized_IAM_ZONE_CONNCANFD_E_CONTROLLER_0_IAM_Tx          27u
#define PDUR_SRCPDU_COM_synthesized_IAM_ZONE_CONNCA_0000_CONTROLLER_0_IAM_Tx          28u
#define PDUR_SRCPDU_COM_synthesized_IAM_ZONE_CONNCA_0001_CONTROLLER_0_IAM_Tx          29u
#define PDUR_SRCPDU_COM_synthesized_IAM_BKPCANFD_20ms_Fr_CONTROLLER_0_IAM_Tx          30u
#define PDUR_SRCPDU_Dcm_phy_tx_0x719          31u
#define PDUR_SRCPDU_CANIF_SDM_SFCANFD_Event_FrS14_CONTROLLER_0_IAM_Rx          32u
#define PDUR_SRCPDU_CANIF_ICBAD_BKPCANFD_Event_FrS04_CONTROLLER_0_IAM_Rx          33u
#define PDUR_SRCPDU_CANIF_ICBAD_BKPCANFD_Event_FrS05_CONTROLLER_0_IAM_Rx          34u
#define PDUR_SRCPDU_CANIF_ICBVC_SecOC_ComKeyReq_CONTROLLER_0_IAM_Rx          35u
#define PDUR_SRCPDU_CANIF_ICBAD_ZONE_CHCANFD_20ms_FrP13_CONTROLLER_0_IAM_Rx          36u
#define PDUR_SRCPDU_CANIF_TC_ZONE_PTCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx          37u
#define PDUR_SRCPDU_CANIF_ICM_INFOCANFD_EvtInfo_CONTROLLER_0_IAM_Rx          38u
#define PDUR_SRCPDU_CANIF_AMP_INFOCAN_EvtInfo_CONTROLLER_0_IAM_Rx          39u
#define PDUR_SRCPDU_CANIF_ECM_ERCANFD_10ms_FrP00_CONTROLLER_0_IAM_Rx          40u
#define PDUR_SRCPDU_CANIF_LHZCU_LHBKBCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx          41u
#define PDUR_SRCPDU_CANIF_RZCU_PTCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx          42u
#define PDUR_SRCPDU_CANIF_IBS_CHCANFD_10ms_FrP04_CONTROLLER_0_IAM_Rx          43u
#define PDUR_SRCPDU_CANIF_PEU_PTCANFD_10ms_FrP04_SigGWtoCO_CONTROLLER_0_IAM_Rx          44u
#define PDUR_SRCPDU_CANIF_DLP_BDCAN_EvtInfo_CONTROLLER_0_IAM_Rx          45u
#define PDUR_SRCPDU_CANIF_PEU_PTCANFD_5ms_FrP02_SigGwTOCON_CONTROLLER_0_IAM_Rx          46u
#define PDUR_SRCPDU_CANIF_TC_PTCANFD_10ms_FrP01_SigGWTORZC_CONTROLLER_0_IAM_Rx          47u
#define PDUR_SRCPDU_CANIF_RZCU_RZCUCANFD_10ms_FrP22_NoSecO_CONTROLLER_0_IAM_Rx          48u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_20ms_FrP01_CONTROLLER_0_IAM_Rx          49u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_20ms_FrP02_CONTROLLER_0_IAM_Rx          50u
#define PDUR_SRCPDU_CANIF_ICBAD_CHCANFD_20ms_FrP08_CONTROLLER_0_IAM_Rx          51u
#define PDUR_SRCPDU_CANIF_PEU_ERCANFD_20ms_FrP33_CONTROLLER_0_IAM_Rx          52u
#define PDUR_SRCPDU_CANIF_SDM_CHCANFD_20ms_FrP01_CONTROLLER_0_IAM_Rx          53u
#define PDUR_SRCPDU_CANIF_ICBVC_RZCUCANFD_20ms_FrP00_CONTROLLER_0_IAM_Rx          54u
#define PDUR_SRCPDU_CANIF_PEU_PTCANFD_100ms_FrP03_CONTROLLER_0_IAM_Rx          55u
#define PDUR_SRCPDU_CANIF_ICBAD_BKPCANFD_20ms_FrP07_CONTROLLER_0_IAM_Rx          56u
#define PDUR_SRCPDU_CANIF_SDM_CHCANFD_20ms_FrP02_CONTROLLER_0_IAM_Rx          57u
#define PDUR_SRCPDU_CANIF_RZCU_PTCANFD_20ms_FrP06_CONTROLLER_0_IAM_Rx          58u
#define PDUR_SRCPDU_CANIF_IBS_CHCANFD_20ms_FrP07_CONTROLLER_0_IAM_Rx          59u
#define PDUR_SRCPDU_CANIF_ICBAD_RZCUCANFD_20ms_FrP12_CONTROLLER_0_IAM_Rx          60u
#define PDUR_SRCPDU_CANIF_IBS_CHCANFD_20ms_FrP11_CONTROLLER_0_IAM_Rx          61u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_20ms_FrP04_CONTROLLER_0_IAM_Rx          62u
#define PDUR_SRCPDU_CANIF_ICBVC_RZCUCANFD_20ms_FrP03_CONTROLLER_0_IAM_Rx          63u
#define PDUR_SRCPDU_CANIF_PEU_PTCANFD_50ms_FrP05_CONTROLLER_0_IAM_Rx          64u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_50ms_FrP14_CONTROLLER_0_IAM_Rx          65u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP29_CONTROLLER_0_IAM_Rx          66u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP26_CONTROLLER_0_IAM_Rx          67u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_50ms_FrP06_CONTROLLER_0_IAM_Rx          68u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_50ms_FrP07_CONTROLLER_0_IAM_Rx          69u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_50ms_FrP09_CONTROLLER_0_IAM_Rx          70u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_50ms_FrP13_CONTROLLER_0_IAM_Rx          71u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_50ms_FrP08_CONTROLLER_0_IAM_Rx          72u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP21_CONTROLLER_0_IAM_Rx          73u
#define PDUR_SRCPDU_CANIF_RZCU_LHBKBCANFD_50ms_FrP37_CONTROLLER_0_IAM_Rx          74u
#define PDUR_SRCPDU_CANIF_LHZCU_LHBKBCANFD_50ms_FrP04_CONTROLLER_0_IAM_Rx          75u
#define PDUR_SRCPDU_CANIF_LHZCU_BKBCANFD_50ms_FrP24_CONTROLLER_0_IAM_Rx          76u
#define PDUR_SRCPDU_CANIF_LHZCU_LHBKBCANFD_50ms_FrP06_CONTROLLER_0_IAM_Rx          77u
#define PDUR_SRCPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP33_CONTROLLER_0_IAM_Rx          78u
#define PDUR_SRCPDU_CANIF_PEU_ERCANFD_50ms_FrP10_CONTROLLER_0_IAM_Rx          79u
#define PDUR_SRCPDU_CANIF_LVBM_PTEXTDCAN_100ms_FrP01_CONTROLLER_0_IAM_Rx          80u
#define PDUR_SRCPDU_CANIF_ICBAD_BKPCANFD_100ms_FrP42_CONTROLLER_0_IAM_Rx          81u
#define PDUR_SRCPDU_CANIF_PEU_ERCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx          82u
#define PDUR_SRCPDU_CANIF_IPD_BKPCANFD_100ms_FrP50_CONTROLLER_0_IAM_Rx          83u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP28_CONTROLLER_0_IAM_Rx          84u
#define PDUR_SRCPDU_CANIF_ESS_ZONE_PTCANFD_100ms_FrP16_CONTROLLER_0_IAM_Rx          85u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP22_CONTROLLER_0_IAM_Rx          86u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP20_CONTROLLER_0_IAM_Rx          87u
#define PDUR_SRCPDU_CANIF_RZCU_PTCANFD_100ms_FrP10_CONTROLLER_0_IAM_Rx          88u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP35_CONTROLLER_0_IAM_Rx          89u
#define PDUR_SRCPDU_CANIF_LHZCU_LHBKBCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx          90u
#define PDUR_SRCPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP23_CONTROLLER_0_IAM_Rx          91u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP36_CONTROLLER_0_IAM_Rx          92u
#define PDUR_SRCPDU_CANIF_ICBVC_FOTASts_100ms_FrP47_CONTROLLER_0_IAM_Rx          93u
#define PDUR_SRCPDU_CANIF_CCU_PTCANFD_100ms_FrP02_CONTROLLER_0_IAM_Rx          94u
#define PDUR_SRCPDU_CANIF_ICBVC_RZCUCANFD_100ms_FrP45_CONTROLLER_0_IAM_Rx          95u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx          96u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_100ms_FrP32_CONTROLLER_0_IAM_Rx          97u
#define PDUR_SRCPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx          98u
#define PDUR_SRCPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx          99u
#define PDUR_SRCPDU_CANIF_ICBVC_RZCUCANFD_100ms_FrP39_CONTROLLER_0_IAM_Rx          100u
#define PDUR_SRCPDU_CANIF_RZCU_LHBKBCANFD_100ms_FrP32_CONTROLLER_0_IAM_Rx          101u
#define PDUR_SRCPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP14_CONTROLLER_0_IAM_Rx          102u
#define PDUR_SRCPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP27_CONTROLLER_0_IAM_Rx          103u
#define PDUR_SRCPDU_CANIF_ICBAD_BKPCANFD_100ms_FrP36_CONTROLLER_0_IAM_Rx          104u
#define PDUR_SRCPDU_CANIF_PEU_ERCANFD_100ms_FrP11_CONTROLLER_0_IAM_Rx          105u
#define PDUR_SRCPDU_CANIF_ICB_BKBCANFD_100ms_FrP221_CONTROLLER_0_IAM_Rx          106u
#define PDUR_SRCPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP13_CONTROLLER_0_IAM_Rx          107u
#define PDUR_SRCPDU_CANIF_ICBVC_RZCUCANFD_100ms_FrP80_CONTROLLER_0_IAM_Rx          108u
#define PDUR_SRCPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP24_CONTROLLER_0_IAM_Rx          109u
#define PDUR_SRCPDU_CANIF_RZCU_RZCUCANFD_100ms_FrP82_CONTROLLER_0_IAM_Rx          110u
#define PDUR_SRCPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP19_CONTROLLER_0_IAM_Rx          111u
#define PDUR_SRCPDU_CANIF_LVBM_PTEXTDCAN_100ms_FrP04_CONTROLLER_0_IAM_Rx          112u
#define PDUR_SRCPDU_CANIF_TC_PTCANFD_100ms_FrP05_CONTROLLER_0_IAM_Rx          113u
#define PDUR_SRCPDU_CANIF_RZCU_PTCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx          114u
#define PDUR_SRCPDU_CANIF_ICBVC_INFOCANFD_250ms_FrP52_CONTROLLER_0_IAM_Rx          115u
#define PDUR_SRCPDU_CANIF_ICB_RZCUCANFD_100ms_FrP144_CONTROLLER_0_IAM_Rx          116u
#define PDUR_SRCPDU_CANIF_SDM_CHCANFD_100ms_FrP03_CONTROLLER_0_IAM_Rx          117u
#define PDUR_SRCPDU_CANIF_RZCU_IMCU_SFCANFD_100ms_FrP26_CONTROLLER_0_IAM_Rx          118u
#define PDUR_SRCPDU_CANIF_ICBVC_CONNCANFD_200ms_FrP157_CONTROLLER_0_IAM_Rx          119u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_200ms_FrP42_CONTROLLER_0_IAM_Rx          120u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_200ms_FrP39_CONTROLLER_0_IAM_Rx          121u
#define PDUR_SRCPDU_CANIF_ICBAD_BKPCANFD_100ms_FrP38_CONTROLLER_0_IAM_Rx          122u
#define PDUR_SRCPDU_CANIF_CCU_PTEXTDCAN_100ms_FrP06_CONTROLLER_0_IAM_Rx          123u
#define PDUR_SRCPDU_CANIF_RZCU_PTEXTDCAN_100ms_FrP21_CONTROLLER_0_IAM_Rx          124u
#define PDUR_SRCPDU_CANIF_TC_PTCANFD_20ms_FrP08_CONTROLLER_0_IAM_Rx          125u
#define PDUR_SRCPDU_CANIF_LHZCU_LHBKBCANFDF_400ms_FrP18_CONTROLLER_0_IAM_Rx          126u
#define PDUR_SRCPDU_CANIF_ICBVC_RZCUCANFD_200ms_FrP79_CONTROLLER_0_IAM_Rx          127u
#define PDUR_SRCPDU_CANIF_ICBVC_CONNCANFD_Event_FrS145_CONTROLLER_0_IAM_Rx          128u
#define PDUR_SRCPDU_CANIF_LHZCU_LHBDCANFD_Event_FrS48_CONTROLLER_0_IAM_Rx          129u
#define PDUR_SRCPDU_CANIF_LHZCU_LHBDCANFD_Event_FrS49_CONTROLLER_0_IAM_Rx          130u
#define PDUR_SRCPDU_CANIF_ICBVC_RHBKBCANFD_500ms_FrP67_CONTROLLER_0_IAM_Rx          131u
#define PDUR_SRCPDU_CANIF_ZXD_CONNCANFD_Event_FrS220_CONTROLLER_0_IAM_Rx          132u
#define PDUR_SRCPDU_CANIF_ICBVC_RZCUCANFD_200ms_FrP50_CONTROLLER_0_IAM_Rx          133u
#define PDUR_SRCPDU_CANIF_ICB_CONNCANFD_Event_FrS67_CONTROLLER_0_IAM_Rx          134u
#define PDUR_SRCPDU_CANIF_synthesized_ICBVC_SecOC_SyncMsg__CONTROLLER_0_IAM_Rx          135u
#define PDUR_SRCPDU_CANIF_RHZCU_BKBCANFD_Event_FrS37_CONTROLLER_0_IAM_Rx          136u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_Event_FrS452_CONTROLLER_0_IAM_Rx          137u
#define PDUR_SRCPDU_CANIF_IPD_BKPCANFD_Event_FrS35_CONTROLLER_0_IAM_Rx          138u
#define PDUR_SRCPDU_CANIF_CCU_PTCANFD_500ms_FrP13_CONTROLLER_0_IAM_Rx          139u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_500ms_FrP60_CONTROLLER_0_IAM_Rx          140u
#define PDUR_SRCPDU_CANIF_ICBVC_CONNCANFD_Event_FrS139_CONTROLLER_0_IAM_Rx          141u
#define PDUR_SRCPDU_CANIF_SDM_SFCANFD_Event_FrS13_CONTROLLER_0_IAM_Rx          142u
#define PDUR_SRCPDU_CANIF_SDM_SFCANFD_Event_FrS12_CONTROLLER_0_IAM_Rx          143u
#define PDUR_SRCPDU_CANIF_ICB_CONNCANFD_EvtInfo_CONTROLLER_0_IAM_Rx          144u
#define PDUR_SRCPDU_CANIF_ESS_PTCANFD_EvtInfo_CONTROLLER_0_IAM_Rx          145u
#define PDUR_SRCPDU_CANIF_DIAG_DTCInfo_ECM_CONTROLLER_0_IAM_Rx          146u
#define PDUR_SRCPDU_CANIF_DIAG_DTCInfo_PEU_CONTROLLER_0_IAM_Rx          147u
#define PDUR_SRCPDU_CANIF_DIAG_DTCInfo_ESS_CONTROLLER_0_IAM_Rx          148u
#define PDUR_SRCPDU_CANIF_DIAG_DTCInfo_TC_CONTROLLER_0_IAM_Rx          149u
#define PDUR_SRCPDU_CanTp_phy_rx_0x711          150u
#define PDUR_SRCPDU_CanTp_fun_rx_0x7df          151u
#define PDUR_SRCPDU_Com_NmUserDataPdu_IAM          152u
#define PDUR_SRCPDU_IpduM_Contained_Tx_Pdu_0x377          153u
#define PDUR_SRCPDU_Com_Contained_Tx_0x377_Pdu06          154u
#define PDUR_SRCPDU_Com_Contained_Tx_0x377_Pdu07          155u
#define PDUR_SRCPDU_Com_Contained_Tx_0x377_Pdu08          156u
#define PDUR_SRCPDU_IpduM_Contained_Tx_Pdu_0x36A          157u
#define PDUR_SRCPDU_Com_Contained_Tx_0x36A_Pdu13          158u
#define PDUR_SRCPDU_Com_Contained_Tx_0x36A_Pdu34          159u
#define PDUR_SRCPDU_Com_Contained_Tx_0x36A_Pdu35          160u
#define PDUR_SRCPDU_Com_Contained_Tx_0x36A_Pdu39          161u
#define PDUR_SRCPDU_Com_Contained_Tx_0x36A_Pdu40          162u
#define PDUR_SRCPDU_IpduM_Contained_Tx_Pdu_0x3A2          163u
#define PDUR_SRCPDU_Com_Contained_Tx_0x3A2_Pdu03          164u
#define PDUR_SRCPDU_Com_Contained_Tx_0x3A2_Pdu04          165u
#define PDUR_SRCPDU_Com_Contained_Tx_0x3A2_Pdu41          166u
#define PDUR_SRCPDU_Com_Contained_Tx_0x3A2_Pdu57          167u
#define PDUR_SRCPDU_CAN0_Rx_SecOC_SyncMsg_0x56F_SecOC_Authentic          168u
#define PDUR_SRCPDU_SecOC_synthesized_IAM_BKPCANFD_20ms_Fr_CONTROLLER_0_IAM_TxSecured          169u
#define PDUR_SRCPDU_SecOC_synthesized_IAM_ZONE_CONNCA_0001_CONTROLLER_0_IAM_TxSecured          170u
#define PDUR_SRCPDU_SecOC_synthesized_IAM_ZONE_CONNCA_0000_CONTROLLER_0_IAM_TxSecured          171u
#define PDUR_SRCPDU_SecOC_synthesized_IAM_ZONE_CONNCANFD_E_CONTROLLER_0_IAM_TxSecured          172u

#define PDUR_DEST_PDU_SUM              173u

#define PDUR_DESTPDU_CANIF_DIAG_DTCInfo_IAM_CONTROLLER_0_IAM_Tx          0u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP60_CONTROLLER_0_IAM_Tx          1u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP61_CONTROLLER_0_IAM_Tx          2u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP62_CONTROLLER_0_IAM_Tx          3u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP63_CONTROLLER_0_IAM_Tx          4u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP64_CONTROLLER_0_IAM_Tx          5u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP65_CONTROLLER_0_IAM_Tx          6u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP66_CONTROLLER_0_IAM_Tx          7u
#define PDUR_DESTPDU_CANIF_IAM_CONNCAN_100ms_FrP18_CONTROLLER_0_IAM_Tx          8u
#define PDUR_DESTPDU_CANIF_IAM_CONNCAN_200ms_FrP01_CONTROLLER_0_IAM_Tx          9u
#define PDUR_DESTPDU_CANIF_IAM_CONNCAN_200ms_FrP02_CONTROLLER_0_IAM_Tx          10u
#define PDUR_DESTPDU_CANIF_IAM_CONNCAN_Event_FrS20_CONTROLLER_0_IAM_Tx          11u
#define PDUR_DESTPDU_CANIF_IAM_CONNCAN_Event_FrS21_CONTROLLER_0_IAM_Tx          12u
#define PDUR_DESTPDU_CANIF_IAM_CONNCANFD_100ms_FrP19_CONTROLLER_0_IAM_Tx          13u
#define PDUR_DESTPDU_CANIF_IAM_CONNCANFD_Event_FrS04_CONTROLLER_0_IAM_Tx          14u
#define PDUR_DESTPDU_CANIF_IAM_CONNCANFD_Event_FrS42_CONTROLLER_0_IAM_Tx          15u
#define PDUR_DESTPDU_CANIF_IAM_CONNCANFD_Event_FrS43_CONTROLLER_0_IAM_Tx          16u
#define PDUR_DESTPDU_CANIF_IAM_CONNCANFD_Event_FrS44_CONTROLLER_0_IAM_Tx          17u
#define PDUR_DESTPDU_CANIF_IAM_CONNCANFD_EvtInfo_CONTROLLER_0_IAM_Tx          18u
#define PDUR_DESTPDU_CANIF_IAM_SecOC_ComKeyResp_CONTROLLER_0_IAM_Tx          19u
#define PDUR_DESTPDU_CANIF_IAM_SecOC_Log_CONTROLLER_0_IAM_Tx          20u
#define PDUR_DESTPDU_CANIF_IAM_ZONE_CONNCANFD_100ms_FrP56_CONTROLLER_0_IAM_Tx          21u
#define PDUR_DESTPDU_CANIF_TBOX_CONNCAN_20ms_FrP02_CONTROLLER_0_IAM_Tx          22u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP49_CONTROLLER_0_IAM_Tx          23u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP55_CONTROLLER_0_IAM_Tx          24u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP58_CONTROLLER_0_IAM_Tx          25u
#define PDUR_DESTPDU_CANIF_IAM_BKPCANFD_1000ms_FrP59_CONTROLLER_0_IAM_Tx          26u
#define PDUR_DESTPDU_CANIF_synthesized_IAM_ZONE_CONNCANFD_E_CONTROLLER_0_IAM_Tx          27u
#define PDUR_DESTPDU_CANIF_synthesized_IAM_ZONE_CONNCA_0000_CONTROLLER_0_IAM_Tx          28u
#define PDUR_DESTPDU_CANIF_synthesized_IAM_ZONE_CONNCA_0001_CONTROLLER_0_IAM_Tx          29u
#define PDUR_DESTPDU_CANIF_synthesized_IAM_BKPCANFD_20ms_Fr_CONTROLLER_0_IAM_Tx          30u
#define PDUR_DESTPDU_CanTp_phy_tx_0x719          31u
#define PDUR_DESTPDU_COM_SDM_SFCANFD_Event_FrS14_CONTROLLER_0_IAM_Rx          32u
#define PDUR_DESTPDU_COM_ICBAD_BKPCANFD_Event_FrS04_CONTROLLER_0_IAM_Rx          33u
#define PDUR_DESTPDU_COM_ICBAD_BKPCANFD_Event_FrS05_CONTROLLER_0_IAM_Rx          34u
#define PDUR_DESTPDU_COM_ICBVC_SecOC_ComKeyReq_CONTROLLER_0_IAM_Rx          35u
#define PDUR_DESTPDU_COM_ICBAD_ZONE_CHCANFD_20ms_FrP13_CONTROLLER_0_IAM_Rx          36u
#define PDUR_DESTPDU_COM_TC_ZONE_PTCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx          37u
#define PDUR_DESTPDU_COM_ICM_INFOCANFD_EvtInfo_CONTROLLER_0_IAM_Rx          38u
#define PDUR_DESTPDU_COM_AMP_INFOCAN_EvtInfo_CONTROLLER_0_IAM_Rx          39u
#define PDUR_DESTPDU_COM_ECM_ERCANFD_10ms_FrP00_CONTROLLER_0_IAM_Rx          40u
#define PDUR_DESTPDU_COM_LHZCU_LHBKBCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx          41u
#define PDUR_DESTPDU_COM_RZCU_PTCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx          42u
#define PDUR_DESTPDU_COM_IBS_CHCANFD_10ms_FrP04_CONTROLLER_0_IAM_Rx          43u
#define PDUR_DESTPDU_COM_PEU_PTCANFD_10ms_FrP04_SigGWtoCO_CONTROLLER_0_IAM_Rx          44u
#define PDUR_DESTPDU_COM_DLP_BDCAN_EvtInfo_CONTROLLER_0_IAM_Rx          45u
#define PDUR_DESTPDU_COM_PEU_PTCANFD_5ms_FrP02_SigGwTOCON_CONTROLLER_0_IAM_Rx          46u
#define PDUR_DESTPDU_COM_TC_PTCANFD_10ms_FrP01_SigGWTORZC_CONTROLLER_0_IAM_Rx          47u
#define PDUR_DESTPDU_COM_RZCU_RZCUCANFD_10ms_FrP22_NoSecO_CONTROLLER_0_IAM_Rx          48u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_20ms_FrP01_CONTROLLER_0_IAM_Rx          49u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_20ms_FrP02_CONTROLLER_0_IAM_Rx          50u
#define PDUR_DESTPDU_COM_ICBAD_CHCANFD_20ms_FrP08_CONTROLLER_0_IAM_Rx          51u
#define PDUR_DESTPDU_COM_PEU_ERCANFD_20ms_FrP33_CONTROLLER_0_IAM_Rx          52u
#define PDUR_DESTPDU_COM_SDM_CHCANFD_20ms_FrP01_CONTROLLER_0_IAM_Rx          53u
#define PDUR_DESTPDU_COM_ICBVC_RZCUCANFD_20ms_FrP00_CONTROLLER_0_IAM_Rx          54u
#define PDUR_DESTPDU_COM_PEU_PTCANFD_100ms_FrP03_CONTROLLER_0_IAM_Rx          55u
#define PDUR_DESTPDU_COM_ICBAD_BKPCANFD_20ms_FrP07_CONTROLLER_0_IAM_Rx          56u
#define PDUR_DESTPDU_COM_SDM_CHCANFD_20ms_FrP02_CONTROLLER_0_IAM_Rx          57u
#define PDUR_DESTPDU_COM_RZCU_PTCANFD_20ms_FrP06_CONTROLLER_0_IAM_Rx          58u
#define PDUR_DESTPDU_COM_IBS_CHCANFD_20ms_FrP07_CONTROLLER_0_IAM_Rx          59u
#define PDUR_DESTPDU_COM_ICBAD_RZCUCANFD_20ms_FrP12_CONTROLLER_0_IAM_Rx          60u
#define PDUR_DESTPDU_COM_IBS_CHCANFD_20ms_FrP11_CONTROLLER_0_IAM_Rx          61u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_20ms_FrP04_CONTROLLER_0_IAM_Rx          62u
#define PDUR_DESTPDU_COM_ICBVC_RZCUCANFD_20ms_FrP03_CONTROLLER_0_IAM_Rx          63u
#define PDUR_DESTPDU_COM_PEU_PTCANFD_50ms_FrP05_CONTROLLER_0_IAM_Rx          64u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_50ms_FrP14_CONTROLLER_0_IAM_Rx          65u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP29_CONTROLLER_0_IAM_Rx          66u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP26_CONTROLLER_0_IAM_Rx          67u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_50ms_FrP06_CONTROLLER_0_IAM_Rx          68u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_50ms_FrP07_CONTROLLER_0_IAM_Rx          69u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_50ms_FrP09_CONTROLLER_0_IAM_Rx          70u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_50ms_FrP13_CONTROLLER_0_IAM_Rx          71u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_50ms_FrP08_CONTROLLER_0_IAM_Rx          72u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP21_CONTROLLER_0_IAM_Rx          73u
#define PDUR_DESTPDU_COM_RZCU_LHBKBCANFD_50ms_FrP37_CONTROLLER_0_IAM_Rx          74u
#define PDUR_DESTPDU_COM_LHZCU_LHBKBCANFD_50ms_FrP04_CONTROLLER_0_IAM_Rx          75u
#define PDUR_DESTPDU_COM_LHZCU_BKBCANFD_50ms_FrP24_CONTROLLER_0_IAM_Rx          76u
#define PDUR_DESTPDU_COM_LHZCU_LHBKBCANFD_50ms_FrP06_CONTROLLER_0_IAM_Rx          77u
#define PDUR_DESTPDU_COM_ESS_PTEXTDCAN_100ms_FrP33_CONTROLLER_0_IAM_Rx          78u
#define PDUR_DESTPDU_COM_PEU_ERCANFD_50ms_FrP10_CONTROLLER_0_IAM_Rx          79u
#define PDUR_DESTPDU_COM_LVBM_PTEXTDCAN_100ms_FrP01_CONTROLLER_0_IAM_Rx          80u
#define PDUR_DESTPDU_COM_ICBAD_BKPCANFD_100ms_FrP42_CONTROLLER_0_IAM_Rx          81u
#define PDUR_DESTPDU_COM_PEU_ERCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx          82u
#define PDUR_DESTPDU_COM_IPD_BKPCANFD_100ms_FrP50_CONTROLLER_0_IAM_Rx          83u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP28_CONTROLLER_0_IAM_Rx          84u
#define PDUR_DESTPDU_COM_ESS_ZONE_PTCANFD_100ms_FrP16_CONTROLLER_0_IAM_Rx          85u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP22_CONTROLLER_0_IAM_Rx          86u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP20_CONTROLLER_0_IAM_Rx          87u
#define PDUR_DESTPDU_COM_RZCU_PTCANFD_100ms_FrP10_CONTROLLER_0_IAM_Rx          88u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP35_CONTROLLER_0_IAM_Rx          89u
#define PDUR_DESTPDU_COM_LHZCU_LHBKBCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx          90u
#define PDUR_DESTPDU_COM_ESS_PTEXTDCAN_100ms_FrP23_CONTROLLER_0_IAM_Rx          91u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP36_CONTROLLER_0_IAM_Rx          92u
#define PDUR_DESTPDU_COM_ICBVC_FOTASts_100ms_FrP47_CONTROLLER_0_IAM_Rx          93u
#define PDUR_DESTPDU_COM_CCU_PTCANFD_100ms_FrP02_CONTROLLER_0_IAM_Rx          94u
#define PDUR_DESTPDU_COM_ICBVC_RZCUCANFD_100ms_FrP45_CONTROLLER_0_IAM_Rx          95u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx          96u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_100ms_FrP32_CONTROLLER_0_IAM_Rx          97u
#define PDUR_DESTPDU_COM_RHZCU_RHBKBCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx          98u
#define PDUR_DESTPDU_COM_RHZCU_RHBKBCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx          99u
#define PDUR_DESTPDU_COM_ICBVC_RZCUCANFD_100ms_FrP39_CONTROLLER_0_IAM_Rx          100u
#define PDUR_DESTPDU_COM_RZCU_LHBKBCANFD_100ms_FrP32_CONTROLLER_0_IAM_Rx          101u
#define PDUR_DESTPDU_COM_RHZCU_RHBKBCANFD_100ms_FrP14_CONTROLLER_0_IAM_Rx          102u
#define PDUR_DESTPDU_COM_ESS_PTEXTDCAN_100ms_FrP27_CONTROLLER_0_IAM_Rx          103u
#define PDUR_DESTPDU_COM_ICBAD_BKPCANFD_100ms_FrP36_CONTROLLER_0_IAM_Rx          104u
#define PDUR_DESTPDU_COM_PEU_ERCANFD_100ms_FrP11_CONTROLLER_0_IAM_Rx          105u
#define PDUR_DESTPDU_COM_ICB_BKBCANFD_100ms_FrP221_CONTROLLER_0_IAM_Rx          106u
#define PDUR_DESTPDU_COM_RHZCU_RHBKBCANFD_100ms_FrP13_CONTROLLER_0_IAM_Rx          107u
#define PDUR_DESTPDU_COM_ICBVC_RZCUCANFD_100ms_FrP80_CONTROLLER_0_IAM_Rx          108u
#define PDUR_DESTPDU_COM_ESS_PTEXTDCAN_100ms_FrP24_CONTROLLER_0_IAM_Rx          109u
#define PDUR_DESTPDU_COM_RZCU_RZCUCANFD_100ms_FrP82_CONTROLLER_0_IAM_Rx          110u
#define PDUR_DESTPDU_COM_RHZCU_RHBKBCANFD_100ms_FrP19_CONTROLLER_0_IAM_Rx          111u
#define PDUR_DESTPDU_COM_LVBM_PTEXTDCAN_100ms_FrP04_CONTROLLER_0_IAM_Rx          112u
#define PDUR_DESTPDU_COM_TC_PTCANFD_100ms_FrP05_CONTROLLER_0_IAM_Rx          113u
#define PDUR_DESTPDU_COM_RZCU_PTCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx          114u
#define PDUR_DESTPDU_COM_ICBVC_INFOCANFD_250ms_FrP52_CONTROLLER_0_IAM_Rx          115u
#define PDUR_DESTPDU_COM_ICB_RZCUCANFD_100ms_FrP144_CONTROLLER_0_IAM_Rx          116u
#define PDUR_DESTPDU_COM_SDM_CHCANFD_100ms_FrP03_CONTROLLER_0_IAM_Rx          117u
#define PDUR_DESTPDU_COM_RZCU_IMCU_SFCANFD_100ms_FrP26_CONTROLLER_0_IAM_Rx          118u
#define PDUR_DESTPDU_COM_ICBVC_CONNCANFD_200ms_FrP157_CONTROLLER_0_IAM_Rx          119u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_200ms_FrP42_CONTROLLER_0_IAM_Rx          120u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_200ms_FrP39_CONTROLLER_0_IAM_Rx          121u
#define PDUR_DESTPDU_COM_ICBAD_BKPCANFD_100ms_FrP38_CONTROLLER_0_IAM_Rx          122u
#define PDUR_DESTPDU_COM_CCU_PTEXTDCAN_100ms_FrP06_CONTROLLER_0_IAM_Rx          123u
#define PDUR_DESTPDU_COM_RZCU_PTEXTDCAN_100ms_FrP21_CONTROLLER_0_IAM_Rx          124u
#define PDUR_DESTPDU_COM_TC_PTCANFD_20ms_FrP08_CONTROLLER_0_IAM_Rx          125u
#define PDUR_DESTPDU_COM_LHZCU_LHBKBCANFDF_400ms_FrP18_CONTROLLER_0_IAM_Rx          126u
#define PDUR_DESTPDU_COM_ICBVC_RZCUCANFD_200ms_FrP79_CONTROLLER_0_IAM_Rx          127u
#define PDUR_DESTPDU_COM_ICBVC_CONNCANFD_Event_FrS145_CONTROLLER_0_IAM_Rx          128u
#define PDUR_DESTPDU_COM_LHZCU_LHBDCANFD_Event_FrS48_CONTROLLER_0_IAM_Rx          129u
#define PDUR_DESTPDU_COM_LHZCU_LHBDCANFD_Event_FrS49_CONTROLLER_0_IAM_Rx          130u
#define PDUR_DESTPDU_COM_ICBVC_RHBKBCANFD_500ms_FrP67_CONTROLLER_0_IAM_Rx          131u
#define PDUR_DESTPDU_COM_ZXD_CONNCANFD_Event_FrS220_CONTROLLER_0_IAM_Rx          132u
#define PDUR_DESTPDU_COM_ICBVC_RZCUCANFD_200ms_FrP50_CONTROLLER_0_IAM_Rx          133u
#define PDUR_DESTPDU_COM_ICB_CONNCANFD_Event_FrS67_CONTROLLER_0_IAM_Rx          134u
#define PDUR_DESTPDU_COM_synthesized_ICBVC_SecOC_SyncMsg__CONTROLLER_0_IAM_Rx          135u
#define PDUR_DESTPDU_COM_RHZCU_BKBCANFD_Event_FrS37_CONTROLLER_0_IAM_Rx          136u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_Event_FrS452_CONTROLLER_0_IAM_Rx          137u
#define PDUR_DESTPDU_COM_IPD_BKPCANFD_Event_FrS35_CONTROLLER_0_IAM_Rx          138u
#define PDUR_DESTPDU_COM_CCU_PTCANFD_500ms_FrP13_CONTROLLER_0_IAM_Rx          139u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_500ms_FrP60_CONTROLLER_0_IAM_Rx          140u
#define PDUR_DESTPDU_COM_ICBVC_CONNCANFD_Event_FrS139_CONTROLLER_0_IAM_Rx          141u
#define PDUR_DESTPDU_COM_SDM_SFCANFD_Event_FrS13_CONTROLLER_0_IAM_Rx          142u
#define PDUR_DESTPDU_COM_SDM_SFCANFD_Event_FrS12_CONTROLLER_0_IAM_Rx          143u
#define PDUR_DESTPDU_COM_ICB_CONNCANFD_EvtInfo_CONTROLLER_0_IAM_Rx          144u
#define PDUR_DESTPDU_COM_ESS_PTCANFD_EvtInfo_CONTROLLER_0_IAM_Rx          145u
#define PDUR_DESTPDU_COM_DIAG_DTCInfo_ECM_CONTROLLER_0_IAM_Rx          146u
#define PDUR_DESTPDU_COM_DIAG_DTCInfo_PEU_CONTROLLER_0_IAM_Rx          147u
#define PDUR_DESTPDU_COM_DIAG_DTCInfo_ESS_CONTROLLER_0_IAM_Rx          148u
#define PDUR_DESTPDU_COM_DIAG_DTCInfo_TC_CONTROLLER_0_IAM_Rx          149u
#define PDUR_DESTPDU_Dcm_phy_rx_0x711          150u
#define PDUR_DESTPDU_Dcm_fun_rx_0x7df          151u
#define PDUR_DESTPDU_CanNm_UserDataPdu_IAM          152u
#define PDUR_DESTPDU_CanIf_Contained_Tx_Pdu_0x377          153u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x377_Pdu06          154u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x377_Pdu07          155u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x377_Pdu08          156u
#define PDUR_DESTPDU_CanIf_Contained_Tx_Pdu_0x36A          157u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x36A_Pdu13          158u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x36A_Pdu34          159u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x36A_Pdu35          160u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x36A_Pdu39          161u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x36A_Pdu40          162u
#define PDUR_DESTPDU_CanIf_Contained_Tx_Pdu_0x3A2          163u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x3A2_Pdu03          164u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x3A2_Pdu04          165u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x3A2_Pdu41          166u
#define PDUR_DESTPDU_IpduM_Contained_Tx_0x3A2_Pdu57          167u
#define PDUR_DESTPDU_CAN0_Rx_SecOC_SyncMsg_0x56F_SecOC_Secured          168u
#define PDUR_DESTPDU_SecOC_synthesized_IAM_BKPCANFD_20ms_Fr_CONTROLLER_0_IAM_TxAuthentic          169u
#define PDUR_DESTPDU_SecOC_synthesized_IAM_ZONE_CONNCA_0001_CONTROLLER_0_IAM_TxAuthentic          170u
#define PDUR_DESTPDU_SecOC_synthesized_IAM_ZONE_CONNCA_0000_CONTROLLER_0_IAM_TxAuthentic          171u
#define PDUR_DESTPDU_SecOC_synthesized_IAM_ZONE_CONNCANFD_E_CONTROLLER_0_IAM_TxAuthentic          172u

#define PDUR_ROUTING_PATH_GROUP_SUM        1u

#define PduRRoutingPathGroup_Diag          0u

#define PDUR_DEFAULT_VALUE_LENGTH           0u
#define PDUR_DEFAULT_VALUE_PDU                  0u

#define PDUR_COMMUNICATION_INTERFACE_FORWARDING_ENABLED       STD_ON
#define PDUR_COMMUNICATION_INTERFACE_GATEWAYING_ENABLED       STD_OFF
#define PDUR_TRANSPORT_PROTOCOL_FORWARDING_NOBUFFERED_ENABLED STD_ON
#define PDUR_TRANSPORT_PROTOCOL_FORWARDING_BUFFERED_ENABLED   STD_OFF
#define PDUR_TRANSPORT_PROTOCOL_GATEWAYING_ENABLED            STD_OFF

#endif  /* end of PDUR_CFG_H */

/*******************************************************************************
**                      End of file                                           **
*******************************************************************************/

