#CC-RH Compiler RH850 Assembler Source
#@	CC-RH Version : V2.07.00  [06 Dec 2024]
#@	Command : ..\..\Bsw\Config\BSW_Config\RH850F1K\Os_Core_Cfg.c -oDefaultBuild\Os_Core_Cfg.obj -Xcpu=g3kh -Xno_warning=20188,20111 -g -g_line -I..\..\Srcode\app\diagnostic -I..\..\Srcode\app\parameter_store -I..\..\Cpu\port -I..\..\Cpu\uart -I..\..\Cpu\iic -I..\..\Srcode\app\vehicle_data_to_mpu -I..\..\Srcode\app\power_manage -I..\..\Srcode\app\mcu_cpu_sync -I..\..\Srcode\app\remote_control -I..\..\Srcode\app\can_cycle_send -I..\..\Srcode\app\project_configure -I..\..\Srcode\sdk\include -I..\..\Srcode\commonLib\include -I..\..\Srcode\hal\include -I..\..\Bsw\Mcal\icu\include -I..\..\Bsw\Config\MCAL_Config\Icu_OutPut\include -I..\..\Bsw\Crypto\CRYPTO\vss -I..\..\ASW\CDD_FVM -I..\..\Bsw\Memory\EEIf -I..\..\Bsw\Communication\CAN\CanTSyn -I..\..\Bsw\SystemServices\StbM -I..\..\Bsw\Crypto\CSM -I..\..\Bsw\Crypto\CRYPTO\RSA -I..\..\Bsw\Crypto\CRYPTO\RandomGen\CTR_DRBG -I..\..\Bsw\Crypto\CRYPTO\MAC\CMAC -I..\..\Bsw\Crypto\CRYPTO\Hash\sha256 -I..\..\Bsw\Crypto\CRYPTO\dh -I..\..\Bsw\Crypto\CRYPTO\AES -I..\..\Bsw\Crypto\CRYPTO -I..\..\Bsw\Crypto\CryInterface -I..\..\Bsw\Communication\Common\SecOC -I..\..\Bsw\Memory\NvM -I..\..\Bsw\Memory\MemIf -I..\..\Bsw\Memory\Fee -I..\..\Bsw\SystemServices\WdgM -I..\..\Bsw\SystemServices\WdgIf -I..\..\Bsw\Config\MCAL_Config\Wdg_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Gpt_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Fls_OutPut\include -I..\..\Bsw\Mcal\wdg\include -I..\..\Bsw\Mcal\gpt\include -I..\..\Bsw\Mcal\fls\include -I..\..\Bsw\Communication\Common\IpduM -I..\..\ASW\APP -I..\..\Bsw\SystemServices\BswM -I..\..\ASW\BSW_Ext -I..\..\Bsw\Communication\Common\Dcm -I..\..\Bsw\Communication\CAN\CanTp -I..\..\Bsw\SystemServices\Dem -I..\..\Bsw\Libraries\E2E -I..\..\Bsw\Libraries\Crc -I..\..\Bsw\Communication\Common\NmIf -I..\..\Bsw\Communication\CAN\CanNm -I..\..\Bsw\Config\BSW_Config\RTE\Rte -I..\..\Bsw\Config\BSW_Config\RTE\SchM -I..\..\Bsw\Libraries\IStd -I..\..\Bsw\SystemServices\EcuM -I..\..\Bsw\SystemServices\ComM -I..\..\Bsw\Communication\CAN\CanSM -I..\..\Bsw\Communication\CAN\CanIf -I..\..\Bsw\Communication\Common\Com -I..\..\Bsw\Communication\Common\PDUR -I..\..\Cpu -I..\..\Bsw\CommonInclude -I..\..\Bsw\Config\BSW_Config -I..\..\Bsw\Config\BSW_Config\RH850F1K -I..\..\Bsw\SystemServices\Os\Extend\inc -I..\..\Bsw\SystemServices\Os\Kernel\inc -I..\..\Bsw\SystemServices\Os\Portable\Mcu -I..\..\Bsw\SystemServices\Os\Portable\Processor -I..\..\Bsw\Config\MCAL_Config\Adc_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Can_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Dio_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Mcu_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Port_OutPut\include -I..\..\Bsw\Mcal\adc\include -I..\..\Bsw\Mcal\can\include -I..\..\Bsw\Mcal\dio\include -I..\..\Bsw\Mcal\general -I..\..\Bsw\Mcal\mcu\include -I..\..\Bsw\Mcal\port\include -I..\..\Bsw\Mcal\stubs\CanGeneral\include -I..\..\Bsw\Mcal\stubs\Det\include -I..\..\Bsw\Mcal\stubs\MemIf\include -I..\..\Bsw\Mcal\stubs\SchM\include -DRH850_F1KM_S1_2MB -lang=c99 -Xfloat=fpu -Xround=zero -Xdiv -Xasm_path=DefaultBuild -Xasm_option=-Xprn_path=DefaultBuild -c -MAKEUD=DefaultBuild -Xexec_time=C:\Users\xlchen\AppData\Local\Temp\CSPlusBuildTool_305b9e4159b54ca6993a59b51d4a0f865gsbnkm2.ujn
#@	compiled at Fri Mar 27 09:51:08 2026

	.file "..\..\Bsw\Config\BSW_Config\RH850F1K\Os_Core_Cfg.c"

	$reg_mode 32
	.dbl_size 8

	.public _Os_IntInstall, 336
	.extern _Os_ISR_SystemTimer_Core_0_Handler0
	.extern _Os_ISR_RCAN1ERR_IRQ_Handler
	.extern _Os_ISR_RCAN1TRX_IRQ_Handler
	.extern _Os_ISR_RCANGRECC0_IRQ_Handler
	.extern _Os_ISR_ADCA0I1_IRQ_Handler
	.extern _Os_ISR_ADCA1I1_IRQ_Handler
	.extern _Os_ISR_TAUJ0I0_IRQ_Handler
	.extern _Os_ISR_TAUD0I9_IRQ_Handler
	.extern _Os_ISR_TAUB0I12_IRQ_Handler
	.extern _Os_ISR_TAUB0I8_IRQ_Handler
	.extern _Os_ISR_TAUB0I9_IRQ_Handler
	.extern _Os_ISR_P1_IRQ_Handler
	.extern _Os_ISR_P2_IRQ_Handler
	.extern _Os_ISR_P5_IRQ_Handler
	.extern _Os_ISR_P6_IRQ_Handler
	.extern _Os_ISR_P7_IRQ_Handler
	.extern _Os_ISR_P9_IRQ_Handler
	.extern _Os_ISR_P14_IRQ_Handler
	.extern _Os_ISR_RLIN34TX0_IRQ_Handler
	.extern _Os_ISR_RLIN34RX1_IRQ_Handler
	.extern _Os_ISR_RLIN34ERR2_IRQ_Handler
	.extern _Os_ISR_RLIN35TX0_IRQ_Handler
	.extern _Os_ISR_RLIN35RX1_IRQ_Handler
	.extern _Os_ISR_RLIN35ERR2_IRQ_Handler
	.extern _Os_ISR_RIIC0TI_IRQ_Handler
	.extern _Os_ISR_RIIC0EE_IRQ_Handler
	.extern _Os_ISR_RIIC0RI_IRQ_Handler
	.extern _Os_ISR_RIIC0TEI_IRQ_Handler

	.section .const, const
	.align 4
_Os_IntInstall:
	.db 0x0A
	.ds (3)
	.dw #_Os_ISR_SystemTimer_Core_0_Handler0
	.dhw 0x008E
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_RCAN1ERR_IRQ_Handler
	.dhw 0x0071
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_RCAN1TRX_IRQ_Handler
	.dhw 0x0073
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_RCANGRECC0_IRQ_Handler
	.dhw 0x0017
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_ADCA0I1_IRQ_Handler
	.dhw 0x0013
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_ADCA1I1_IRQ_Handler
	.dhw 0x00D6
	.dhw 0xFFFF
	.db 0x04
	.ds (3)
	.dw #_Os_ISR_TAUJ0I0_IRQ_Handler
	.dhw 0x0050
	.dhw 0xFFFF
	.db 0x04
	.ds (3)
	.dw #_Os_ISR_TAUD0I9_IRQ_Handler
	.dhw 0x0034
	.dhw 0xFFFF
	.db 0x04
	.ds (3)
	.dw #_Os_ISR_TAUB0I12_IRQ_Handler
	.dhw 0x009A
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_TAUB0I8_IRQ_Handler
	.dhw 0x0096
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_TAUB0I9_IRQ_Handler
	.dhw 0x0097
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_P1_IRQ_Handler
	.dhw 0x0026
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_P2_IRQ_Handler
	.dhw 0x0027
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_P5_IRQ_Handler
	.dhw 0x002D
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_P6_IRQ_Handler
	.dhw 0x0080
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_P7_IRQ_Handler
	.dhw 0x0081
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_P9_IRQ_Handler
	.dhw 0x00CD
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_P14_IRQ_Handler
	.dhw 0x00CF
	.dhw 0xFFFF
	.db 0x03
	.ds (3)
	.dw #_Os_ISR_RLIN34TX0_IRQ_Handler
	.dhw 0x00E9
	.dhw 0xFFFF
	.db 0x01
	.ds (3)
	.dw #_Os_ISR_RLIN34RX1_IRQ_Handler
	.dhw 0x00EA
	.dhw 0xFFFF
	.db 0x01
	.ds (3)
	.dw #_Os_ISR_RLIN34ERR2_IRQ_Handler
	.dhw 0x00EB
	.dhw 0xFFFF
	.db 0x05
	.ds (3)
	.dw #_Os_ISR_RLIN35TX0_IRQ_Handler
	.dhw 0x00ED
	.dhw 0xFFFF
	.db 0x08
	.ds (3)
	.dw #_Os_ISR_RLIN35RX1_IRQ_Handler
	.dhw 0x00EE
	.dhw 0xFFFF
	.db 0x01
	.ds (3)
	.dw #_Os_ISR_RLIN35ERR2_IRQ_Handler
	.dhw 0x00EF
	.dhw 0xFFFF
	.db 0x01
	.ds (3)
	.dw #_Os_ISR_RIIC0TI_IRQ_Handler
	.dhw 0x004C
	.dhw 0xFFFF
	.db 0x01
	.ds (3)
	.dw #_Os_ISR_RIIC0EE_IRQ_Handler
	.dhw 0x004D
	.dhw 0xFFFF
	.db 0x01
	.ds (3)
	.dw #_Os_ISR_RIIC0RI_IRQ_Handler
	.dhw 0x004E
	.dhw 0xFFFF
	.db 0x01
	.ds (3)
	.dw #_Os_ISR_RIIC0TEI_IRQ_Handler
	.dhw 0x004F
	.dhw 0xFFFF
