#CC-RH Compiler RH850 Assembler Source
#@	CC-RH Version : V2.07.00  [06 Dec 2024]
#@	Command : ..\..\Bsw\Config\BSW_Config\PduR_Cfg.c -oDefaultBuild\PduR_Cfg.obj -Xcpu=g3kh -Xno_warning=20188,20111 -g -g_line -I..\..\Srcode\app\diagnostic -I..\..\Srcode\app\parameter_store -I..\..\Cpu\port -I..\..\Cpu\uart -I..\..\Cpu\iic -I..\..\Srcode\app\vehicle_data_to_mpu -I..\..\Srcode\app\power_manage -I..\..\Srcode\app\mcu_cpu_sync -I..\..\Srcode\app\remote_control -I..\..\Srcode\app\can_cycle_send -I..\..\Srcode\app\project_configure -I..\..\Srcode\sdk\include -I..\..\Srcode\commonLib\include -I..\..\Srcode\hal\include -I..\..\Bsw\Mcal\icu\include -I..\..\Bsw\Config\MCAL_Config\Icu_OutPut\include -I..\..\Bsw\Crypto\CRYPTO\vss -I..\..\ASW\CDD_FVM -I..\..\Bsw\Memory\EEIf -I..\..\Bsw\Communication\CAN\CanTSyn -I..\..\Bsw\SystemServices\StbM -I..\..\Bsw\Crypto\CSM -I..\..\Bsw\Crypto\CRYPTO\RSA -I..\..\Bsw\Crypto\CRYPTO\RandomGen\CTR_DRBG -I..\..\Bsw\Crypto\CRYPTO\MAC\CMAC -I..\..\Bsw\Crypto\CRYPTO\Hash\sha256 -I..\..\Bsw\Crypto\CRYPTO\dh -I..\..\Bsw\Crypto\CRYPTO\AES -I..\..\Bsw\Crypto\CRYPTO -I..\..\Bsw\Crypto\CryInterface -I..\..\Bsw\Communication\Common\SecOC -I..\..\Bsw\Memory\NvM -I..\..\Bsw\Memory\MemIf -I..\..\Bsw\Memory\Fee -I..\..\Bsw\SystemServices\WdgM -I..\..\Bsw\SystemServices\WdgIf -I..\..\Bsw\Config\MCAL_Config\Wdg_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Gpt_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Fls_OutPut\include -I..\..\Bsw\Mcal\wdg\include -I..\..\Bsw\Mcal\gpt\include -I..\..\Bsw\Mcal\fls\include -I..\..\Bsw\Communication\Common\IpduM -I..\..\ASW\APP -I..\..\Bsw\SystemServices\BswM -I..\..\ASW\BSW_Ext -I..\..\Bsw\Communication\Common\Dcm -I..\..\Bsw\Communication\CAN\CanTp -I..\..\Bsw\SystemServices\Dem -I..\..\Bsw\Libraries\E2E -I..\..\Bsw\Libraries\Crc -I..\..\Bsw\Communication\Common\NmIf -I..\..\Bsw\Communication\CAN\CanNm -I..\..\Bsw\Config\BSW_Config\RTE\Rte -I..\..\Bsw\Config\BSW_Config\RTE\SchM -I..\..\Bsw\Libraries\IStd -I..\..\Bsw\SystemServices\EcuM -I..\..\Bsw\SystemServices\ComM -I..\..\Bsw\Communication\CAN\CanSM -I..\..\Bsw\Communication\CAN\CanIf -I..\..\Bsw\Communication\Common\Com -I..\..\Bsw\Communication\Common\PDUR -I..\..\Cpu -I..\..\Bsw\CommonInclude -I..\..\Bsw\Config\BSW_Config -I..\..\Bsw\Config\BSW_Config\RH850F1K -I..\..\Bsw\SystemServices\Os\Extend\inc -I..\..\Bsw\SystemServices\Os\Kernel\inc -I..\..\Bsw\SystemServices\Os\Portable\Mcu -I..\..\Bsw\SystemServices\Os\Portable\Processor -I..\..\Bsw\Config\MCAL_Config\Adc_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Can_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Dio_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Mcu_OutPut\include -I..\..\Bsw\Config\MCAL_Config\Port_OutPut\include -I..\..\Bsw\Mcal\adc\include -I..\..\Bsw\Mcal\can\include -I..\..\Bsw\Mcal\dio\include -I..\..\Bsw\Mcal\general -I..\..\Bsw\Mcal\mcu\include -I..\..\Bsw\Mcal\port\include -I..\..\Bsw\Mcal\stubs\CanGeneral\include -I..\..\Bsw\Mcal\stubs\Det\include -I..\..\Bsw\Mcal\stubs\MemIf\include -I..\..\Bsw\Mcal\stubs\SchM\include -DRH850_F1KM_S1_2MB -lang=c99 -Xfloat=fpu -Xround=zero -Xdiv -Xasm_path=DefaultBuild -Xasm_option=-Xprn_path=DefaultBuild -c -MAKEUD=DefaultBuild -Xexec_time=C:\Users\xlchen\AppData\Local\Temp\CSPlusBuildTool_58169ba76b5d4bd3bccd76778bd2abab0tb3vkhk.ela
#@	compiled at Fri Mar 27 09:50:40 2026

	.file "..\..\Bsw\Config\BSW_Config\PduR_Cfg.c"

	$reg_mode 32
	.dbl_size 8

	.public _PduR_BswModuleConfigData, 392
	.public _PduR_GlobalBufferPool, 8
	.extern _Com_TriggerTransmit
	.extern _Com_TxConfirmation
	.extern _Com_RxIndication
	.extern _Com_CopyTxData
	.extern _Com_TpTxConfirmation
	.extern _Com_StartOfReception
	.extern _Com_CopyRxData
	.extern _Com_TpRxIndication
	.extern _CanIf_Transmit
	.extern _CanNm_Transmit
	.extern _CanTp_Transmit
	.extern _Dcm_TxConfirmation
	.extern _Dcm_CopyTxData
	.extern _Dcm_TpTxConfirmation
	.extern _Dcm_StartOfReception
	.extern _Dcm_CopyRxData
	.extern _Dcm_TpRxIndication
	.extern _IpduM_TriggerTransmit
	.extern _IpduM_Transmit
	.extern _IpduM_TxConfirmation
	.extern _IpduM_RxIndication
	.extern _SecOC_TriggerTransmit
	.extern _SecOC_IfTransmit
	.extern _SecOC_TxConfirmation
	.extern _SecOC_RxIndication
	.extern _SecOC_TpTransmit
	.extern _SecOC_CopyTxData
	.extern _SecOC_TpTxConfirmation
	.extern _SecOC_StartOfReception
	.extern _SecOC_CopyRxData
	.extern _SecOC_TpRxIndication

	.section .const, const
	.align 4
_PduR_BswModuleConfigData:
	.ds (1)
	.ds (3)
	.ds (4)
	.ds (4)
	.ds (4)
	.dw #_Com_TriggerTransmit
	.ds (4)
	.dw #_Com_TxConfirmation
	.dw #_Com_RxIndication
	.ds (4)
	.dw #_Com_CopyTxData
	.dw #_Com_TpTxConfirmation
	.dw #_Com_StartOfReception
	.dw #_Com_CopyRxData
	.dw #_Com_TpRxIndication
	.db 0x01
	.ds (3)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.dw #_CanIf_Transmit
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.db 0x02
	.ds (3)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.dw #_CanNm_Transmit
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.db 0x03
	.ds (3)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.dw #_CanTp_Transmit
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.db 0x04
	.ds (3)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.dw #_Dcm_TxConfirmation
	.ds (4)
	.ds (4)
	.dw #_Dcm_CopyTxData
	.dw #_Dcm_TpTxConfirmation
	.dw #_Dcm_StartOfReception
	.dw #_Dcm_CopyRxData
	.dw #_Dcm_TpRxIndication
	.db 0x05
	.ds (3)
	.ds (4)
	.ds (4)
	.ds (4)
	.dw #_IpduM_TriggerTransmit
	.dw #_IpduM_Transmit
	.dw #_IpduM_TxConfirmation
	.dw #_IpduM_RxIndication
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.ds (4)
	.db 0x06
	.ds (3)
	.ds (4)
	.ds (4)
	.ds (4)
	.dw #_SecOC_TriggerTransmit
	.dw #_SecOC_IfTransmit
	.dw #_SecOC_TxConfirmation
	.dw #_SecOC_RxIndication
	.dw #_SecOC_TpTransmit
	.dw #_SecOC_CopyTxData
	.dw #_SecOC_TpTxConfirmation
	.dw #_SecOC_StartOfReception
	.dw #_SecOC_CopyRxData
	.dw #_SecOC_TpRxIndication
	.align 4
_PduR_GlobalBufferPool:
	.ds (8)
