/**
 * Copyright (C) 2024 Isoft Infrastructure Software Co., Ltd.
 * SPDX-License-Identifier: LGPL-2.1-only-with-exception OR  LicenseRef-Commercial-License
 *
 * This library is free software; you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation; version 2.1.
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License along with this library;
 * if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 * or see <https://www.gnu.org/licenses/>.
 *
 * Alternatively, this file may be used under the terms of the Isoft Infrastructure Software Co., Ltd.
 * Commercial License, in which case the provisions of the Isoft Infrastructure Software Co., Ltd.
 * Commercial License shall apply instead of those of the GNU Lesser General Public License.
 *
 * You should have received a copy of the Isoft Infrastructure Software Co., Ltd.  Commercial License
 * along with this program. If not, please find it at <https://EasyXMen.com/xy/reference/permissions.html>
 *
 ************************************************************************************************************************
 **
 **  @file               : Os_Sprot.h
 **  @author             : i-soft-os
 **  @date               : 2024/02/10
 **  @vendor             : isoft
 **  @description        : Os header file for Sprot api declarations
 **
 ***********************************************************************************************************************/

#ifndef OS_SPROT_H
#define OS_SPROT_H

/* =================================================== inclusions =================================================== */
#include "Os_Types.h"

/**
 * @brief Service protection check items, high 16 bits
 */
#define OS_SERVICEPROT_CHECK_BIT_WRITABLE (0x00080000U)
#define OS_SERVICEPROT_CHECK_BIT_OBJACS (0x00040000U)
#define OS_SERVICEPROT_CHECK_BIT_IGNORE (0x00020000U)
#define OS_SERVICEPROT_CHECK_BIT_CONTEXT (0x00010000U)

/**
 * @brief Service calls condtion in context.
          Service Protection Level Bit
          OS_LEVEL_BIT_ERRORHOOK_APP 0x0400U   100 0000 0000
          OS_LEVEL_BIT_TASK 0x0200U            010 0000 0000
          OS_LEVEL_BIT_ISR1 0x0100U            001 0000 0000
          OS_LEVEL_BIT_ISR2 0x0080U            000 1000 0000
          OS_LEVEL_BIT_ERRORHOOK 0x0040U       000 0100 0000
          OS_LEVEL_BIT_PRETASKHOOK 0x0020U     000 0010 0000
          OS_LEVEL_BIT_POSTTASKHOOK 0x0010U    000 0001 0000
          OS_LEVEL_BIT_STARTUPHOOK 0x0008U     000 0000 1000
          OS_LEVEL_BIT_SHUTDOWNHOOK 0x0004U    000 0000 0100
          OS_LEVEL_BIT_ALARMCALLBACK 0x0002U   000 0000 0010
          OS_LEVEL_BIT_PROTECTIONHOOK 0x0001U  000 0000 0001
 */
/**
 * @brief Service calls condtion in context.
 */
#define OS_CONTEXT_ACTIVATE_TASK 0x0280U                 /* 010 1000 0000*/
#define OS_CONTEXT_ACTIVATE_TASK_ASYN 0x0280U            /* 010 1000 0000*/
#define OS_CONTEXT_TERMINATE_TASK 0x0200U                /* 010 0000 0000*/
#define OS_CONTEXT_CHAIN_TASK 0x0200U                    /* 010 0000 0000*/
#define OS_CONTEXT_SCHEDULE 0x0200U                      /* 010 0000 0000*/
#define OS_CONTEXT_GET_TASK_ID 0x06F1U                   /* 110 1111 0001*/
#define OS_CONTEXT_GET_TASK_STATE 0x06F0U                /* 110 1111 0000*/
#define OS_CONTEXT_DISABLE_ALL_INTERRUPTS 0x07FFU        /* 111 1111 1111*/
#define OS_CONTEXT_ENABLE_ALL_INTERRUPTS 0x07FFU         /* 111 1111 1111*/
#define OS_CONTEXT_SUSPEND_ALL_INTERRUPTS 0x07FFU        /* 111 1111 1111*/
#define OS_CONTEXT_RESUME_ALL_INTERRUPTS 0x07FFU         /* 111 1111 1111*/
#define OS_CONTEXT_SUSPEND_OS_INTERRUPTS 0x07FFU         /* 111 1111 1111*/
#define OS_CONTEXT_RESUME_OS_INTERRUPTS 0x07FFU          /* 111 1111 1111*/
#define OS_CONTEXT_DISABLE_INTERRUPT_SOURCE 0x0280U      /* 010 1000 0000*/
#define OS_CONTEXT_ENABLE_INTERRUPT_SOURCE 0x0280U       /* 010 1000 0000*/
#define OS_CONTEXT_CLEAR_PENDING_INTERRUPT 0x0280U       /* 010 1000 0000*/
#define OS_CONTEXT_GET_RESOURCE 0x0280U                  /* 010 1000 0000*/
#define OS_CONTEXT_RELEASE_RESOURCE 0x0280U              /* 010 1000 0000*/
#define OS_CONTEXT_SET_EVENT 0x0280U                     /* 010 1000 0000*/
#define OS_CONTEXT_SET_EVENT_ASYN 0x0280U                /* 010 1000 0000*/
#define OS_CONTEXT_CLEAR_EVENT 0x0280U                   /* 010 0000 0000*/
#define OS_CONTEXT_GET_EVENT 0x06F0U                     /* 110 1111 0000*/
#define OS_CONTEXT_WAIT_EVENT 0x0200U                    /* 010 0000 0000*/
#define OS_CONTEXT_WAIT_ALL_EVENTS 0x0200U               /* 010 0000 0000*/
#define OS_CONTEXT_GET_ALARM_BASE 0x06F0U                /* 110 1111 0000*/
#define OS_CONTEXT_GET_ALARM 0x06F0U                     /* 110 1111 0000*/
#define OS_CONTEXT_SET_REL_ALARM 0x0280U                 /* 010 1000 0000*/
#define OS_CONTEXT_SET_ABS_ALARM 0x0280U                 /* 010 1000 0000*/
#define OS_CONTEXT_CANCEL_ALARM 0x0280U                  /* 010 1000 0000*/
#define OS_CONTEXT_GET_ACTIV_APPLICATION_MODE 0x06FCU    /* 110 1111 1100*/
#define OS_CONTEXT_START_OS 0x0000U                      /* 000 0000 0000*/
#define OS_CONTEXT_SHUTDOWN_OS 0x06C8U                   /* 110 1100 1000*/
#define OS_CONTEXT_GET_APPLICATION_ID 0x06FDU            /* 110 1111 1101*/
#define OS_CONTEXT_GET_ISR_ID 0x06C1U                    /* 110 1100 0001*/
#define OS_CONTEXT_CALL_TRUSTED_FUNCTION 0x0280U         /* 010 1000 0000*/
#define OS_CONTEXT_CHECK_ISR_MEMORY_ACCESS 0x06C1U       /* 110 1100 0001*/
#define OS_CONTEXT_CHECK_TASK_MEMORY_ACCESS 0x06C1U      /* 110 1100 0001*/
#define OS_CONTEXT_CHECK_OBJECT_ACCESS 0x06C1U           /* 110 1100 0001*/
#define OS_CONTEXT_CHECK_OBJECT_OWNERSHIP 0x06C1U        /* 110 1100 0001*/
#define OS_CONTEXT_START_ST_REL 0x0280U                  /* 010 1000 0000*/
#define OS_CONTEXT_START_ST_ABS 0x0280U                  /* 010 1000 0000*/
#define OS_CONTEXT_STOP_SCHEDULE_TABLE 0x0280U           /* 010 1000 0000*/
#define OS_CONTEXT_NEXT_SCHEDULE_TABLE 0x0280U           /* 010 1000 0000*/
#define OS_CONTEXT_START_ST_SYN 0x0280U                  /* 010 1000 0000*/
#define OS_CONTEXT_SYNC_SCHEDULE_TABLE 0x0280U           /* 010 1000 0000*/
#define OS_CONTEXT_GET_SCHEDULE_TABLE_STATUS 0x0280U     /* 010 1000 0000*/
#define OS_CONTEXT_SET_SCHEDULE_TABLE_ASYNC 0x0280U      /* 010 1000 0000*/
#define OS_CONTEXT_INCREMENT_COUNTER 0x0280U             /* 010 1000 0000*/
#define OS_CONTEXT_GET_COUNTER_VALUE 0x0280U             /* 110 1000 0000*/
#define OS_CONTEXT_GET_ELAPSED_COUNTER_VALUE 0x0280U     /* 110 1000 0000*/
#define OS_CONTEXT_TERMINATE_APPLICATION 0x06C0U         /* 110 1100 0000*/
#define OS_CONTEXT_ALLOW_ACCESS 0x0280U                  /* 110 1000 0000*/
#define OS_CONTEXT_GET_APPLICATION_STATE 0x06FDU         /* 110 1111 1101*/
#define OS_CONTEXT_CONTROL_IDLE 0x0280U                  /* 110 1000 0000*/
#define OS_CONTEXT_GET_CURRENT_APPLICATION_ID 0x06FDU    /* 110 1111 1101*/
#define OS_CONTEXT_GET_NUMBER_OF_ACTIVATED_CORES 0x0280U /* 110 1000 0000*/
#define OS_CONTEXT_GET_CORE_ID 0x07FFU                   /* 111 1111 1111*/
#define OS_CONTEXT_START_CORE 0x0000U                    /* 000 0000 0000*/
#define OS_CONTEXT_START_NON_AUTOSAR_CORE 0x1000U        /* 100 0000 0000*/
#define OS_CONTEXT_GET_SPINLOCK 0x0280U                  /* 110 1000 0000*/
#define OS_CONTEXT_RELEASE_SPINLOCK 0x0280U              /* 110 1000 0000*/
#define OS_CONTEXT_TRY_TO_GET_SPINLOCK 0x0280U           /* 110 1000 0000*/
#define OS_CONTEXT_SHUTDOWN_ALLCORES 0x06C8U             /* 110 1100 1000*/
#define OS_CONTEXT_OPEARTION_PERIPHERAL 0x0280U          /* 010 1000 0000*/
#define OS_CONTEXT_GETEXCEPTIONCONTEXT 0x0001U           /* 000 0000 0001*/
#define OS_CONTEXT_SETEXCEPTIONCONTEXT 0x0001U           /* 000 0000 0001*/
#define OS_CONTEXT_GETUNHANDLEDIRQ 0x02FFU               /* 010 1111 1111*/
#define OS_CONTEXT_GETUNHANDLEDEXE 0x02FFU               /* 010 1111 1111*/
#define OS_CONTEXT_BARRIERSYNCHRONIZE 0x0200U            /* 010 0000 0000*/

/**
 * @brief The service protection of the check items to the API
 */
#define OS_SERVICEPORT_CHECK_ACTIVATE_TASK (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_ACTIVATE_TASK)

#define OS_SERVICEPORT_CHECK_ACTIVATE_TASK_ASYN (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_ACTIVATE_TASK_ASYN)

#define OS_SERVICEPORT_CHECK_TERMINATE_TASK (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_TERMINATE_TASK)

#define OS_SERVICEPORT_CHECK_CHAIN_TASK (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_CHAIN_TASK)

#define OS_SERVICEPORT_CHECK_SCHEDULE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_SCHEDULE)

#define OS_SERVICEPORT_CHECK_GET_TASK_ID (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_CONTEXT_GET_TASK_ID)

#define OS_SERVICEPORT_CHECK_GET_TASK_STATE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_TASK_STATE)

#define OS_SERVICEPORT_CHECK_DISABLE_INTERRUPT_SOURCE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_DISABLE_INTERRUPT_SOURCE)

#define OS_SERVICEPORT_CHECK_ENABLE_INTERRUPT_SOURCE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_ENABLE_INTERRUPT_SOURCE)

#define OS_SERVICEPORT_CHECK_CLEAR_PENDING_INTERRUPT (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_CLEAR_PENDING_INTERRUPT)

#define OS_SERVICEPORT_CHECK_GET_RESOURCE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_RESOURCE)

#define OS_SERVICEPORT_CHECK_RELEASE_RESOURCE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_RELEASE_RESOURCE)

#define OS_SERVICEPORT_CHECK_SET_EVENT (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_SET_EVENT)

#define OS_SERVICEPORT_CHECK_SET_EVENT_ASYN (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_SET_EVENT_ASYN)

#define OS_SERVICEPORT_CHECK_CLEAR_EVENT (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_CLEAR_EVENT)

#define OS_SERVICEPORT_CHECK_GET_EVENT (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_CONTEXT_GET_EVENT)

#define OS_SERVICEPORT_CHECK_WAIT_EVENT (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_WAIT_EVENT)

#define OS_SERVICEPORT_CHECK_WAIT_ALL_EVENTS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_WAIT_ALL_EVENTS)

#define OS_SERVICEPORT_CHECK_GET_ALARM_BASE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_ALARM_BASE)

#define OS_SERVICEPORT_CHECK_GET_ALARM (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_ALARM)

#define OS_SERVICEPORT_CHECK_SET_REL_ALARM (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_SET_REL_ALARM)

#define OS_SERVICEPORT_CHECK_SET_ABS_ALARM (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_SET_ABS_ALARM)

#define OS_SERVICEPORT_CHECK_CANCEL_ALARM (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_CANCEL_ALARM)

#define OS_SERVICEPORT_CHECK_GET_ACTIV_APPLICATION_MODE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_GET_ACTIV_APPLICATION_MODE)

#define OS_SERVICEPORT_CHECK_SHUTDOWN_OS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_SHUTDOWN_OS)

#define OS_SERVICEPORT_CHECK_GET_APPLICATION_ID (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_GET_APPLICATION_ID)

#define OS_SERVICEPORT_CHECK_GET_ISR_ID (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_GET_ISR_ID)

#define OS_SERVICEPORT_CHECK_CALL_TRUSTED_FUNCTION (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_CONTEXT_CALL_TRUSTED_FUNCTION)

#define OS_SERVICEPORT_CHECK_TASK_MEMORY_ACCESS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE |OS_CONTEXT_CHECK_TASK_MEMORY_ACCESS)

#define OS_SERVICEPORT_CHECK_ISR_MEMORY_ACCESS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_CHECK_ISR_MEMORY_ACCESS)

#define OS_SERVICEPORT_CHECK_OBJECT_ACCESS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_CHECK_OBJECT_ACCESS)

#define OS_SERVICEPORT_CHECK_OBJECT_OWNERSHIP (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_CHECK_OBJECT_OWNERSHIP)

#define OS_SERVICEPORT_CHECK_START_ST_REL (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_START_ST_REL)

#define OS_SERVICEPORT_CHECK_START_ST_ABS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_START_ST_ABS)

#define OS_SERVICEPORT_CHECK_STOP_SCHEDULE_TABLE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_STOP_SCHEDULE_TABLE)

#define OS_SERVICEPORT_CHECK_NEXT_SCHEDULE_TABLE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_NEXT_SCHEDULE_TABLE)

#define OS_SERVICEPORT_CHECK_START_ST_SYN (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_START_ST_SYN)

#define OS_SERVICEPORT_CHECK_SYNC_SCHEDULE_TABLE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_SYNC_SCHEDULE_TABLE)

#define OS_SERVICEPORT_CHECK_GET_SCHEDULE_TABLE_STATUS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_SCHEDULE_TABLE_STATUS)

#define OS_SERVICEPORT_CHECK_SET_SCHEDULE_TABLE_ASYNC (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_SET_SCHEDULE_TABLE_ASYNC)

#define OS_SERVICEPORT_CHECK_INCREMENT_COUNTER (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_INCREMENT_COUNTER)

#define OS_SERVICEPORT_CHECK_GET_COUNTER_VALUE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_COUNTER_VALUE)

#define OS_SERVICEPORT_CHECK_GET_ELAPSED_COUNTER_VALUE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_ELAPSED_COUNTER_VALUE)

#define OS_SERVICEPORT_CHECK_TERMINATE_APPLICATION (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_TERMINATE_APPLICATION)

#define OS_SERVICEPORT_CHECK_ALLOW_ACCESS (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_ALLOW_ACCESS)

#define OS_SERVICEPORT_CHECK_GET_APPLICATION_STATE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_WRITABLE | OS_CONTEXT_GET_APPLICATION_STATE)

#define OS_SERVICEPORT_CHECK_CONTROL_IDLE (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_CONTROL_IDLE)

#define OS_SERVICEPORT_CHECK_GET_CURRENT_APPLICATION_ID (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_GET_CURRENT_APPLICATION_ID)

#define OS_SERVICEPORT_CHECK_GET_ACTIVATEED_CORE_NUMBER (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_GET_NUMBER_OF_ACTIVATED_CORES)

#define OS_SERVICEPORT_CHECK_GET_SPINLOCK (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_GET_SPINLOCK)

#define OS_SERVICEPORT_CHECK_TRY_TO_GET_SPINLOCK (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_TRY_TO_GET_SPINLOCK)

#define OS_SERVICEPORT_CHECK_RELEASE_SPINLOCK (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_OBJACS | OS_CONTEXT_RELEASE_SPINLOCK)

#define OS_SERVICEPORT_CHECK_SHUTDOWN_ALLCORES (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_SERVICEPROT_CHECK_BIT_IGNORE | OS_CONTEXT_SHUTDOWN_ALLCORES)

#define OS_SERVICEPORT_CHECK_OPEARTION_PERIPHERAL (OS_SERVICEPROT_CHECK_BIT_CONTEXT | OS_CONTEXT_OPEARTION_PERIPHERAL)

/* ========================================= external function declarations ========================================= */
/**
 * @brief              When the task is not completed normally,
 *                     the OS will enter this function to terminate the task.
 * @synchronous        TRUE
 * @reentrant          FALSE
 * @trace              -
 */
extern void Os_TaskErrBack(void);

#if (TRUE == CFG_SERVICE_PROTECTION_ENABLE)
/**
 * @brief              Service protection checks call context, access permissions, etc.
 * @param[in]          pScb: Points to the system control block.
 * @param[in]          servicePortParam: Parameters for service protection check.
 * @return             StatusType
 * @synchronous        TRUE
 * @reentrant          TRUE
 * @trace              -
 */
extern StatusType Os_ServiceProtCheck(const Os_SCBType *pScb, const Os_ServicePortParamType *servicePortParam);

/**
 * @brief              If interrupts are disabled/suspended, OS service should ignore.
 * @param[in]          pScb: Points to the system control block.
 * @return             boolean
 * @synchronous        TRUE
 * @reentrant          TRUE
 * @trace              -
 */
extern boolean Os_IgnoreService(const Os_SCBType *pScb);

/**
 * @brief              Indicate the address if writable by this OS-App.
 * @param[in]          pScb: Points to the system control block.
 * @param[in]          address: The address that needs to be checked.
 * @return             boolean
 * @synchronous        TRUE
 * @reentrant          TRUE
 * @trace              -
 */
extern boolean Os_AddressWritable(const Os_SCBType *pScb, uint32 address);

/**
 * @brief              Indicate the service if in right context.
 * @param[in]          pScb: Points to the system control block.
 * @param[in]          allowedContext: Context for allowing invocation.
 * @return             boolean
 * @synchronous        TRUE
 * @reentrant          TRUE
 * @trace              -
 */
extern boolean Os_WrongContext(const Os_SCBType *pScb, uint16 allowedContext);

/**
 * @brief              ISR2 ends with locked interrupts or allocated
 *                     resources.
 * @param[in]          isrId: The isrId that needs to be checked.
 * @synchronous        TRUE
 * @reentrant          TRUE
 * @trace              -
 */
extern void Os_Isr2OccupyIntRes(Os_IsrType isrId);

/**
 * @brief              Check object access to the calling Task/Isr2.
 * @param[in]          pScb: Points to the system control block.
 * @param[in]          objectType: The type of object that needs to be checked.
 * @param[in]          objectID: The objectId that needs to be checked.
 * @return             boolean
 * @synchronous        TRUE
 * @reentrant          TRUE 
 * @trace              -
 */
extern boolean Os_CheckObjAcs(const Os_SCBType *pScb, ObjectTypeType objectType, Os_AppObjectId objectID);

#endif

#endif

/*=======[E N D   O F   F I L E]==============================================*/
