/**
 * COPYRIGHT
 * ---------------------------------------------------------------------------------------------------------------------
 * Copyright (c) iSOFT INFRASTRUCTURE SOFTWARE CO., LTD. This software is proprietary to
 * iSOFT INFRASTRUCTURE SOFTWARE CO., LTD., and all rights are reserved by iSOFT INFRASTRUCTURE SOFTWARE CO., LTD.
 * Without the express written permission of the company, no organization or individual may copy, install, trial,
 * distribute, or reverse engineer this software. For terms of use and further details, please refer to the End User
 * License Agreement (EULA) or contact us business@i-soft.com.cn for more assistance.
 *
 * This file contains code from iSoft, which is licensed under the LGPL-2.1. However, due to a special exception,
 * you are not required to comply with the provisions of section 6a of LGPL-2.1. Specifically, you may distribute
 * your software, including this file, under terms of your choice, including proprietary licenses, without needing to
 * provide the source code or object code as specified in section 6a. For more details, please refer to the project's
 * LICENSE and EXCEPTION files and the specific exception statement.
 * ---------------------------------------------------------------------------------------------------------------------
 * FILE DESCRIPTION
 * ---------------------------------------------------------------------------------------------------------------------
 * @MCU               : R7F7015833
 * @file              : Rte.h
 * @license           : 
 * @licenseExpiryDate : 
 * @date              : 2026-01-16 11:47:28
 * @customer          : iSoft
 * @description       : Header file containing RTE types
 * @toolVersion       : 2.2.0.3
 **********************************************************************************************************************/
#ifndef RTE_H
#define RTE_H
/* ================================================ misar justifications ============================================ */
/**
  \page ISOFT_MISRA_Exceptions  MISRA-C:2012 Compliance Exceptions
    ModeName:Rte
  RuleSorce:puhua_rules-2024.12.rcf
      
    \li VL_Rte_SimilarIdentifier
      Reason: The name is determined by the configuration.
      Risk: Older compilers may interpret it as the same identifier.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_DeadLoop
      Reason: The loop exits only after the Callback function has finished executing.
      Risk: It may cause blocking.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_Redeclaration
      Reason: Rte.c need function declaration to use and Xfrm module need either.
      Risk: Code redundancy and may difficult to maintain
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_AlwaysTrue
      Reason: Generation because of the configurations.
      Risk: Code redundancy and may difficult to maintain
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_AlwaysFalse
      Reason: Generation because of the configurations.
      Risk: Code redundancy and may difficult to maintain
      Prevention: Code inspection and test of the different configurations in the component test.
    
    \li VL_Rte_DiffDataType
      Reason: DataType is determined by the configuration.
      Risk: Code redundancy and may difficult to maintain
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_GlobalVarUsed
      Reason: The number of times GlobalVar is used depends on the configuration.
      Risk: Code redundancy and may difficult to maintain
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_VarInitTypeDiff
      Reason: The Initvalue of Var is depends on the configuration.
      Risk: Code redundancy and may difficult to maintain
      Prevention: Configuration should be right.

    \li VL_Rte_MaCroDefExpression
      Reason: Macro definitions such as error reporting and offset calculation are multi-line definitions.
      Risk: The macro defines format requirements, no risk.
      Prevention: Correctness and reliability have been guaranteed through unit and functional testing.

    \li VL_Rte_UnLinked
      Reason: The usage of this file depends on the config
      Risk: Code redundancy and may difficult to maintain.
      Prevention: Functional reliability guaranteed by design.

    \li VL_Rte_RedundantCode
      Reason: The code is generated by the tool,The architecture needs to be revised, which will have a significant impact.
      Risk: Code redundancy and may difficult to maintain.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_StaticGlobalVariable
      Reason: File scoped variables only used in one function are necessary for functional usage
      Risk: Code redundancy and may difficult to maintain.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_VoidPtrtoObjPtr
      Reason: The ObjPtr type is depends on the configuration.
      Risk: Code redundancy and may difficult to maintain.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_ReturnValNoUsed
      Reason: Return value may be used.
      Risk: Code redundancy and may difficult to maintain.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_FuncNoUsed
      Reason: Func may be used.
      Risk: Code redundancy and may difficult to maintain.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_Standard
      Reason: The AUTOSAR standard specifies this.
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_ArrayAccessOutOfBounds
      Reason: The array size and index is generated according to the configuration
      Risk: Performance reduction and code redundancy.
      Prevention: Functional reliability guaranteed by design.

    \li VL_Rte_NoFuncParaIdentifier
      Reason: Based on the code prescribed by AUTOSAR.
      Risk: Function readability is reduced.
      Prevention: Optionally add comments.
     
    \li VL_Rte_MacroUse
      Reason: The parameter's usage within the macro definition is not parenthesised
      Risk: May produce unexpected behaviour if the text of the argument were to change in future
      Prevention: Enclose the parameters in the macro definition in parentheses.

    \li VL_Rte_Mutitypedef
      Reason: Typedef is depends on the configuration.
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_ParamNoConst
      Reason: The parameter are not modified and so they could be qualified as const.
      Risk: The usage varies in different scenarios.
      Prevention: It will not affect the execution logic of the code.

    \li VL_Rte_FuncCallRedundant
      Reason: Under certain configuration, it would only call one single function.
      Risk: Performance reduction and code redundancy.
      Prevention: Logic remain OK and behave no risk under some other configuration.

    \li VL_Rte_NoDefination
      Reason: Implemented by another module
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_DoWhile
      Reason: the do-while statement is used to enclose macro definition
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_EnumConvert
      Reason: convenient to use general logic to handle  the enumeration definitions for different modules
      Risk: The definition of enumeration values may exceed the range of uint8 values.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_CodeUnreachable
      Reason: Exception Handle
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_DataTypeImplicitConvert
      Reason: Generation because of the configurations.
      Risk: If the symbol number is negative, the value will be unexpected.
      Prevention: The number with a sign is definitely a positive number.

    \li VL_Rte_NumericSuffix
      Reason: The Suffixes were generated by configuration
      Risk: may cause compilation errors or runtime errors.
      Prevention: Modify the configuration

    \li VL_Rte_NoModifyVariable
      Reason: The variables will be modified in dataflow followed
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_VariableNoUse
      Reason: Allow the definition of some unused variables,which defined by configuration
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_UnionDefined
      Reason: The union object is defined by configuration
      Risk: Performance reduction and code redundancy.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_Rte_ArrayQualifier
      Reason: DataType is determined by the configuration.
      Risk: Performance reduction and code redundancy.
      Prevention: C23 support

    \li VL_Rte_UniqueDefinition
      Reason: The objects are in different namespaces
      Risk: Performance reduction and code redundancy.
      Prevention: Ensure through compilation
    
    \li VL_Rte_PointerArithmetic
      Reason: Pointer arithmetic is used to access the elements of an array.
      Risk: Code readability and maintainability may be reduced.
      Prevention: Code inspection and test of the different configurations in the component test.

    \li VL_MTR_Rte_STPAR
      Reason: The API is defined by the AUTOSAR standard. The standard compliance vote is higher than the measurement threshold.
      Risk: For the target uC, the stack usage and runtime are too high.
      Prevention: When testing the result code on the target uC, the user must check the stack usage in the project context.

    \li VL_MTR_Rte_STCYC
      Reason: The functions were not separated into sub-functions because there were higher requirements for minimizing the stack and applying them to the runtime usage of the code
      Risk: Understandability and testability may become overly complex.
      Prevention: Design and code review + clear structure and annotated code.
    
    \li VL_MTR_Rte_STLIN
      Reason: Some function logics are overly complex. Splitting and implementing them will lead to reduced performance.
      Risk: The code is difficult to maintain.
      Prevention: Design and code review, clear structure and annotated code.

    \li VL_MTR_Rte_STMIF
      Reason: Tasks must handle different scenarios based on local conditions, which leads to deep control nesting. Since shared code outweighs the variants, deeper nesting is acceptable to keep the code size small.
      Risk: The code is difficult to maintain.
      Prevention: Design and code review, clear structure and annotated code.
    
    \li VL_MTR_Rte_STST3
      Reason: Some functions logic is too complex; splitting them would degrade performance.
      Risk: The code is difficult to maintain.
      Prevention: Design and code review, clear structure and annotated code.

    \li VL_MTR_Rte_STPTH
      Reason: Functionality wasn't split into subroutines because there are stricter demands on minimizing stack usage and runtime footprint.
      Risk: The code is difficult to maintain.
      Prevention: Design and code review, clear structure and annotated code.

    \li VL_MTR_Rte_STSCT
      Reason: RTE operation requires many static variables.
      Risk: Static variables have global lifetimes; an excess of them can create implicit inter-module dependencies and increase code coupling.
      Prevention: Design and code review, clear structure and annotated code.

    \li VL_MTR_Rte_STCDN
      Reason: Comments adhere to PH standards.
      Risk: A high comment-to-code ratio may indicate that the code is overly complex or verbose.
      Prevention: Reduce reliance on comments by optimizing code logic.

    \li VL_MTR_Rte_STECT
      Reason: The total variable count is tied to user configuration; dynamic code may exceed this under extreme conditions.
      Risk: The code is difficult to maintain, and the data flow is complex.
      Prevention: Design and code review, clear structure and annotated code.

    \li VL_MTR_Rte_STVAR
      Reason: Variable count is tied to user configuration, and dynamic code may exceed it under extreme conditions.
      Risk: The code is difficult to maintain.
      Prevention: Design and code review, clear structure and annotated code.

 */
/*******************************************************************************
**                        RTE Version                                         **
*******************************************************************************/
#define RTE_VENDOR_ID (62U)
#define RTE_MODULE_ID (2U)

#define RTE_AR_RELEASE_MAJOR_VERSION     (4U)
#define RTE_AR_RELEASE_MINOR_VERSION     (5U)
#define RTE_AR_RELEASE_REVISION_VERSION  (0U)

/*******************************************************************************
**                      Include Section                                       **
*******************************************************************************/
#include "Std_Types.h"
#include "ComStack_Types.h"
#include "istd_lib.h"
#include "SchM.h"
#define Rte_MemCpy ILib_memcpy
/*******************************************************************************
**                      Global Macros                                        **
*******************************************************************************/
#define RTE_UINT8_NO_DATA   0xFFU
#define RTE_UINT16_NO_DATA  0xFFFFU
#define RTE_UINT32_NO_DATA  0xFFFFFFFFU 



/* Common Errors */
#define RTE_E_OK               (0U)
#define RTE_E_INVALID          (1U)

/* Overlayed Errors */
#define RTE_E_LOST_DATA        (64U)
#define RTE_E_MAX_AGE_EXCEEDED (64U)

/* Immediate Infrastructure Errors */
#define RTE_E_COM_STOPPED      (128U)
#define RTE_E_TIMEOUT          (129U)
#define RTE_E_LIMIT            (130U)
#define RTE_E_NO_DATA          (131U)
#define RTE_E_TRANSMIT_ACK     (132U)
#define RTE_E_NEVER_RECEIVED   (133U)
#define RTE_E_UNCONNECTED            (134U)
#define RTE_E_IN_EXCLUSIVE_AREA      (135U)
#define RTE_E_SEG_FAULT              (136U)
#define RTE_E_OUT_OF_RANGE           (137U)
#define RTE_E_SERIALIZATION_ERROR    (138U)
#define RTE_E_HARD_TRANSFORMER_ERROR (138U)
#define RTE_E_SERIALIZATION_LIMIT    (139U)
#define RTE_E_TRANSFORMER_LIMIT      (139U)
#define RTE_E_SOFT_TRANSFORMER_ERROR (140U)
#define RTE_E_COM_BUSY               (141U)

/* Macro Error Check */
#define Rte_HasOverlayedError(status) (((status) & 64U) != 0U)
#define Rte_IsInfrastructureError(status) (((status) & 128U) != 0U)
#define Rte_IsHardTransformerError Rte_IsInfrastructureError
#define Rte_ApplicationError(status) ((status) & 63U)

#endif /*RTE_H*/
