/*==============================================================================*/
/**
 *
 * Copyright (C) iSOFT   (2023)
 *
 * All rights reserved.
 *
 * This document contains proprietary information belonging to iSOFT.
 * Passing on and copying of this document, and communication
 * of its contents is not permitted without prior written authorization.
 * 
 ********************************************************************************
 * 
 *  @MCU                : R7F7015833
 *  @file               : CanIf_PBcfg.h
 *  @author             : iSoft
 *  @date               : 2026-04-15 20:37:30
 *  @vendor             : iSoft
 *  @description        : 
 *  @specification(S)   : AUTOSAR Classic Platform R19-11
 *  @toolVersion        : 2.2.0.3
 */
/*==============================================================================*/

#ifndef CANIF_PBCFG_H
#define CANIF_PBCFG_H

/*******************************************************************************
**                      Version Information                                   **
*******************************************************************************/

#define CANIF_CFG_H_AR_RELEASE_MAJOR_VERSION    4u
#define CANIF_CFG_H_AR_RELEASE_MINOR_VERSION    2u
#define CANIF_CFG_H_AR_RELEASE_REVISION_VERSION 2u
#define CANIF_CFG_H_SW_MAJOR_VERSION            2u
#define CANIF_CFG_H_SW_MINOR_VERSION            2u
#define CANIF_CFG_H_SW_PATCH_VERSION            2u

/*******************************************************************************
**                      Macros                                                **
*******************************************************************************/

#define CANIF_RXPDU_NUMBER              137u
#define CANIF_RXPDU_CANIF_SDM_SFCANFD_Event_FrS14_CONTROLLER_0_IAM_Rx         0u
#define CANIF_RXPDU_CANIF_ICBAD_BKPCANFD_Event_FrS04_CONTROLLER_0_IAM_Rx         1u
#define CANIF_RXPDU_CANIF_ICBAD_BKPCANFD_Event_FrS05_CONTROLLER_0_IAM_Rx         2u
#define CANIF_RXPDU_CANIF_ICBVC_SecOC_ComKeyReq_CONTROLLER_0_IAM_Rx         3u
#define CANIF_RXPDU_CANIF_ICBAD_ZONE_CHCANFD_20ms_FrP13_CONTROLLER_0_IAM_Rx         4u
#define CANIF_RXPDU_CANIF_TC_ZONE_PTCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx         5u
#define CANIF_RXPDU_CANIF_ICM_INFOCANFD_EvtInfo_CONTROLLER_0_IAM_Rx         6u
#define CANIF_RXPDU_CANIF_AMP_INFOCAN_EvtInfo_CONTROLLER_0_IAM_Rx         7u
#define CANIF_RXPDU_CANIF_ECM_ERCANFD_10ms_FrP00_CONTROLLER_0_IAM_Rx         8u
#define CANIF_RXPDU_CANIF_LHZCU_LHBKBCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx         9u
#define CANIF_RXPDU_CANIF_RZCU_PTCANFD_10ms_FrP01_CONTROLLER_0_IAM_Rx         10u
#define CANIF_RXPDU_CANIF_IBS_CHCANFD_10ms_FrP04_CONTROLLER_0_IAM_Rx         11u
#define CANIF_RXPDU_CANIF_PEU_PTCANFD_10ms_FrP04_SigGWtoCO_CONTROLLER_0_IAM_Rx         12u
#define CANIF_RXPDU_CANIF_DLP_BDCAN_EvtInfo_CONTROLLER_0_IAM_Rx         13u
#define CANIF_RXPDU_CANIF_PEU_PTCANFD_5ms_FrP02_SigGwTOCON_CONTROLLER_0_IAM_Rx         14u
#define CANIF_RXPDU_CANIF_TC_PTCANFD_10ms_FrP01_SigGWTORZC_CONTROLLER_0_IAM_Rx         15u
#define CANIF_RXPDU_CANIF_RZCU_RZCUCANFD_10ms_FrP22_NoSecO_CONTROLLER_0_IAM_Rx         16u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_20ms_FrP01_CONTROLLER_0_IAM_Rx         17u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_20ms_FrP02_CONTROLLER_0_IAM_Rx         18u
#define CANIF_RXPDU_CANIF_ICBAD_CHCANFD_20ms_FrP08_CONTROLLER_0_IAM_Rx         19u
#define CANIF_RXPDU_CANIF_PEU_ERCANFD_20ms_FrP33_CONTROLLER_0_IAM_Rx         20u
#define CANIF_RXPDU_CANIF_SDM_CHCANFD_20ms_FrP01_CONTROLLER_0_IAM_Rx         21u
#define CANIF_RXPDU_CANIF_ICBVC_RZCUCANFD_20ms_FrP00_CONTROLLER_0_IAM_Rx         22u
#define CANIF_RXPDU_CANIF_PEU_PTCANFD_100ms_FrP03_CONTROLLER_0_IAM_Rx         23u
#define CANIF_RXPDU_CANIF_ICBAD_BKPCANFD_20ms_FrP07_CONTROLLER_0_IAM_Rx         24u
#define CANIF_RXPDU_CANIF_SDM_CHCANFD_20ms_FrP02_CONTROLLER_0_IAM_Rx         25u
#define CANIF_RXPDU_CANIF_RZCU_PTCANFD_20ms_FrP06_CONTROLLER_0_IAM_Rx         26u
#define CANIF_RXPDU_CANIF_IBS_CHCANFD_20ms_FrP07_CONTROLLER_0_IAM_Rx         27u
#define CANIF_RXPDU_CANIF_ICBAD_RZCUCANFD_20ms_FrP12_CONTROLLER_0_IAM_Rx         28u
#define CANIF_RXPDU_CANIF_IBS_CHCANFD_20ms_FrP11_CONTROLLER_0_IAM_Rx         29u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_20ms_FrP04_CONTROLLER_0_IAM_Rx         30u
#define CANIF_RXPDU_CANIF_ICBVC_RZCUCANFD_20ms_FrP03_CONTROLLER_0_IAM_Rx         31u
#define CANIF_RXPDU_CANIF_PEU_PTCANFD_50ms_FrP05_CONTROLLER_0_IAM_Rx         32u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_50ms_FrP14_CONTROLLER_0_IAM_Rx         33u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP29_CONTROLLER_0_IAM_Rx         34u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP26_CONTROLLER_0_IAM_Rx         35u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_50ms_FrP06_CONTROLLER_0_IAM_Rx         36u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_50ms_FrP07_CONTROLLER_0_IAM_Rx         37u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_50ms_FrP09_CONTROLLER_0_IAM_Rx         38u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_50ms_FrP13_CONTROLLER_0_IAM_Rx         39u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_50ms_FrP08_CONTROLLER_0_IAM_Rx         40u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP21_CONTROLLER_0_IAM_Rx         41u
#define CANIF_RXPDU_CANIF_RZCU_LHBKBCANFD_50ms_FrP37_CONTROLLER_0_IAM_Rx         42u
#define CANIF_RXPDU_CANIF_LHZCU_LHBKBCANFD_50ms_FrP04_CONTROLLER_0_IAM_Rx         43u
#define CANIF_RXPDU_CANIF_LHZCU_BKBCANFD_50ms_FrP24_CONTROLLER_0_IAM_Rx         44u
#define CANIF_RXPDU_CANIF_LHZCU_LHBKBCANFD_50ms_FrP06_CONTROLLER_0_IAM_Rx         45u
#define CANIF_RXPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP33_CONTROLLER_0_IAM_Rx         46u
#define CANIF_RXPDU_CANIF_PEU_ERCANFD_50ms_FrP10_CONTROLLER_0_IAM_Rx         47u
#define CANIF_RXPDU_CANIF_LVBM_PTEXTDCAN_100ms_FrP01_CONTROLLER_0_IAM_Rx         48u
#define CANIF_RXPDU_CANIF_ICBAD_BKPCANFD_100ms_FrP42_CONTROLLER_0_IAM_Rx         49u
#define CANIF_RXPDU_CANIF_PEU_ERCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx         50u
#define CANIF_RXPDU_CANIF_IPD_BKPCANFD_100ms_FrP50_CONTROLLER_0_IAM_Rx         51u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP28_CONTROLLER_0_IAM_Rx         52u
#define CANIF_RXPDU_CANIF_ESS_ZONE_PTCANFD_100ms_FrP16_CONTROLLER_0_IAM_Rx         53u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP22_CONTROLLER_0_IAM_Rx         54u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP20_CONTROLLER_0_IAM_Rx         55u
#define CANIF_RXPDU_CANIF_RZCU_PTCANFD_100ms_FrP10_CONTROLLER_0_IAM_Rx         56u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP35_CONTROLLER_0_IAM_Rx         57u
#define CANIF_RXPDU_CANIF_LHZCU_LHBKBCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx         58u
#define CANIF_RXPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP23_CONTROLLER_0_IAM_Rx         59u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP36_CONTROLLER_0_IAM_Rx         60u
#define CANIF_RXPDU_CANIF_ICBVC_FOTASts_100ms_FrP47_CONTROLLER_0_IAM_Rx         61u
#define CANIF_RXPDU_CANIF_CCU_PTCANFD_100ms_FrP02_CONTROLLER_0_IAM_Rx         62u
#define CANIF_RXPDU_CANIF_ICBVC_RZCUCANFD_100ms_FrP45_CONTROLLER_0_IAM_Rx         63u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx         64u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_100ms_FrP32_CONTROLLER_0_IAM_Rx         65u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx         66u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx         67u
#define CANIF_RXPDU_CANIF_ICBVC_RZCUCANFD_100ms_FrP39_CONTROLLER_0_IAM_Rx         68u
#define CANIF_RXPDU_CANIF_RZCU_LHBKBCANFD_100ms_FrP32_CONTROLLER_0_IAM_Rx         69u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP14_CONTROLLER_0_IAM_Rx         70u
#define CANIF_RXPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP27_CONTROLLER_0_IAM_Rx         71u
#define CANIF_RXPDU_CANIF_ICBAD_BKPCANFD_100ms_FrP36_CONTROLLER_0_IAM_Rx         72u
#define CANIF_RXPDU_CANIF_PEU_ERCANFD_100ms_FrP11_CONTROLLER_0_IAM_Rx         73u
#define CANIF_RXPDU_CANIF_ICB_BKBCANFD_100ms_FrP221_CONTROLLER_0_IAM_Rx         74u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP13_CONTROLLER_0_IAM_Rx         75u
#define CANIF_RXPDU_CANIF_ICBVC_RZCUCANFD_100ms_FrP80_CONTROLLER_0_IAM_Rx         76u
#define CANIF_RXPDU_CANIF_ESS_PTEXTDCAN_100ms_FrP24_CONTROLLER_0_IAM_Rx         77u
#define CANIF_RXPDU_CANIF_RZCU_RZCUCANFD_100ms_FrP82_CONTROLLER_0_IAM_Rx         78u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP19_CONTROLLER_0_IAM_Rx         79u
#define CANIF_RXPDU_CANIF_LVBM_PTEXTDCAN_100ms_FrP04_CONTROLLER_0_IAM_Rx         80u
#define CANIF_RXPDU_CANIF_TC_PTCANFD_100ms_FrP05_CONTROLLER_0_IAM_Rx         81u
#define CANIF_RXPDU_CANIF_RZCU_PTCANFD_100ms_FrP12_CONTROLLER_0_IAM_Rx         82u
#define CANIF_RXPDU_CANIF_ICBVC_INFOCANFD_250ms_FrP52_CONTROLLER_0_IAM_Rx         83u
#define CANIF_RXPDU_CANIF_ICB_RZCUCANFD_100ms_FrP144_CONTROLLER_0_IAM_Rx         84u
#define CANIF_RXPDU_CANIF_SDM_CHCANFD_100ms_FrP03_CONTROLLER_0_IAM_Rx         85u
#define CANIF_RXPDU_CANIF_RZCU_IMCU_SFCANFD_100ms_FrP26_CONTROLLER_0_IAM_Rx         86u
#define CANIF_RXPDU_CANIF_ICBVC_CONNCANFD_200ms_FrP157_CONTROLLER_0_IAM_Rx         87u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_200ms_FrP42_CONTROLLER_0_IAM_Rx         88u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_200ms_FrP39_CONTROLLER_0_IAM_Rx         89u
#define CANIF_RXPDU_CANIF_ICBAD_BKPCANFD_100ms_FrP38_CONTROLLER_0_IAM_Rx         90u
#define CANIF_RXPDU_CANIF_CCU_PTEXTDCAN_100ms_FrP06_CONTROLLER_0_IAM_Rx         91u
#define CANIF_RXPDU_CANIF_RZCU_PTEXTDCAN_100ms_FrP21_CONTROLLER_0_IAM_Rx         92u
#define CANIF_RXPDU_CANIF_TC_PTCANFD_20ms_FrP08_CONTROLLER_0_IAM_Rx         93u
#define CANIF_RXPDU_CANIF_LHZCU_LHBKBCANFDF_400ms_FrP18_CONTROLLER_0_IAM_Rx         94u
#define CANIF_RXPDU_CANIF_ICBVC_RZCUCANFD_200ms_FrP79_CONTROLLER_0_IAM_Rx         95u
#define CANIF_RXPDU_CANIF_ICBVC_CONNCANFD_Event_FrS145_CONTROLLER_0_IAM_Rx         96u
#define CANIF_RXPDU_CANIF_LHZCU_LHBDCANFD_Event_FrS48_CONTROLLER_0_IAM_Rx         97u
#define CANIF_RXPDU_CANIF_LHZCU_LHBDCANFD_Event_FrS49_CONTROLLER_0_IAM_Rx         98u
#define CANIF_RXPDU_CANIF_ICBVC_RHBKBCANFD_500ms_FrP67_CONTROLLER_0_IAM_Rx         99u
#define CANIF_RXPDU_CANIF_ZXD_CONNCANFD_Event_FrS220_CONTROLLER_0_IAM_Rx         100u
#define CANIF_RXPDU_CANIF_ICBVC_RZCUCANFD_200ms_FrP50_CONTROLLER_0_IAM_Rx         101u
#define CANIF_RXPDU_CANIF_ICB_CONNCANFD_Event_FrS67_CONTROLLER_0_IAM_Rx         102u
#define CANIF_RXPDU_CANIF_synthesized_ICBVC_SecOC_SyncMsg__CONTROLLER_0_IAM_Rx         103u
#define CANIF_RXPDU_CANIF_RHZCU_BKBCANFD_Event_FrS37_CONTROLLER_0_IAM_Rx         104u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_Event_FrS452_CONTROLLER_0_IAM_Rx         105u
#define CANIF_RXPDU_CANIF_IPD_BKPCANFD_Event_FrS35_CONTROLLER_0_IAM_Rx         106u
#define CANIF_RXPDU_CANIF_CCU_PTCANFD_500ms_FrP13_CONTROLLER_0_IAM_Rx         107u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_500ms_FrP60_CONTROLLER_0_IAM_Rx         108u
#define CANIF_RXPDU_CANIF_ICBVC_CONNCANFD_Event_FrS139_CONTROLLER_0_IAM_Rx         109u
#define CANIF_RXPDU_CANIF_SDM_SFCANFD_Event_FrS13_CONTROLLER_0_IAM_Rx         110u
#define CANIF_RXPDU_CANIF_SDM_SFCANFD_Event_FrS12_CONTROLLER_0_IAM_Rx         111u
#define CANIF_RXPDU_CANIF_ICB_CONNCANFD_EvtInfo_CONTROLLER_0_IAM_Rx         112u
#define CANIF_RXPDU_CANIF_ESS_PTCANFD_EvtInfo_CONTROLLER_0_IAM_Rx         113u
#define CANIF_RXPDU_CANIF_DIAG_DTCInfo_ECM_CONTROLLER_0_IAM_Rx         114u
#define CANIF_RXPDU_CANIF_DIAG_DTCInfo_PEU_CONTROLLER_0_IAM_Rx         115u
#define CANIF_RXPDU_CANIF_DIAG_DTCInfo_ESS_CONTROLLER_0_IAM_Rx         116u
#define CANIF_RXPDU_CANIF_DIAG_DTCInfo_TC_CONTROLLER_0_IAM_Rx         117u
#define CANIF_RXPDU_CanIf_phy_rx_0x711         118u
#define CANIF_RXPDU_CanIf_fun_rx_0x7df         119u
#define CANIF_RXPDU_CANIF_IAM_NM_RxPdu_IAM_NM_RxPdu         120u
#define CANIF_RXPDU_RX_PDU_CANTSYNC         121u
#define CANIF_RXPDU_CANIF_RHZCU_RRDCM_BDCAN_500ms_FrP01_CONTROLLER_0_IAM_Rx         122u
#define CANIF_RXPDU_CANIF_LHZCU_RLDCM_BDCAN_500ms_FrP01_CONTROLLER_0_IAM_Rx         123u
#define CANIF_RXPDU_CANIF_LHZCU_BKBCANFD_400ms_FrP01_CONTROLLER_0_IAM_Rx         124u
#define CANIF_RXPDU_CANIF_LHZCU_BKBCANFD_400ms_FrP03_CONTROLLER_0_IAM_Rx         125u
#define CANIF_RXPDU_CANIF_ICB_RZCUCANFD_200ms_FrP82_CONTROLLER_0_IAM_Rx         126u
#define CANIF_RXPDU_CANIF_ICB_ZONE_BDCAN_100ms_FrP00_CONTROLLER_0_IAM_Rx         127u
#define CANIF_RXPDU_CANIF_LHZCU_BKBCANFD_200ms_FrP50_CONTROLLER_0_IAM_Rx         128u
#define CANIF_RXPDU_CANIF_RZCU_LHBKBCANFD_100ms_FrP38_CONTROLLER_0_IAM_Rx         129u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP10_CONTROLLER_0_IAM_Rx         130u
#define CANIF_RXPDU_CANIF_LHZCU_LHBKBCANFD_100ms_FrP11_CONTROLLER_0_IAM_Rx         131u
#define CANIF_RXPDU_CANIF_LHZCU_BKBCANFD_50ms_FrP34_CONTROLLER_0_IAM_Rx         132u
#define CANIF_RXPDU_CANIF_LHZCU_LHBKBCANFD_50ms_FrP05_CONTROLLER_0_IAM_Rx         133u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_50ms_FrP01_CONTROLLER_0_IAM_Rx         134u
#define CANIF_RXPDU_CANIF_IBS_CHCANFD_100ms_FrP15_CONTROLLER_0_IAM_Rx         135u
#define CANIF_RXPDU_CANIF_RHZCU_RHBKBCANFD_100ms_FrP09_CONTROLLER_0_IAM_Rx         136u
#define CANIF_TXPDU_NUMBER              36u
#define CANIF_DYNAMIC_TXPDU_NUMBER      36u
#define CANIF_TXPDU_CANIF_DIAG_DTCInfo_IAM_CONTROLLER_0_IAM_Tx         0u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP60_CONTROLLER_0_IAM_Tx         1u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP61_CONTROLLER_0_IAM_Tx         2u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP62_CONTROLLER_0_IAM_Tx         3u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP63_CONTROLLER_0_IAM_Tx         4u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP64_CONTROLLER_0_IAM_Tx         5u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP65_CONTROLLER_0_IAM_Tx         6u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP66_CONTROLLER_0_IAM_Tx         7u
#define CANIF_TXPDU_CANIF_IAM_CONNCAN_100ms_FrP18_CONTROLLER_0_IAM_Tx         8u
#define CANIF_TXPDU_CANIF_IAM_CONNCAN_200ms_FrP01_CONTROLLER_0_IAM_Tx         9u
#define CANIF_TXPDU_CANIF_IAM_CONNCAN_200ms_FrP02_CONTROLLER_0_IAM_Tx         10u
#define CANIF_TXPDU_CANIF_IAM_CONNCAN_Event_FrS20_CONTROLLER_0_IAM_Tx         11u
#define CANIF_TXPDU_CANIF_IAM_CONNCAN_Event_FrS21_CONTROLLER_0_IAM_Tx         12u
#define CANIF_TXPDU_CANIF_IAM_CONNCANFD_100ms_FrP19_CONTROLLER_0_IAM_Tx         13u
#define CANIF_TXPDU_CANIF_IAM_CONNCANFD_Event_FrS04_CONTROLLER_0_IAM_Tx         14u
#define CANIF_TXPDU_CANIF_IAM_CONNCANFD_Event_FrS42_CONTROLLER_0_IAM_Tx         15u
#define CANIF_TXPDU_CANIF_IAM_CONNCANFD_Event_FrS43_CONTROLLER_0_IAM_Tx         16u
#define CANIF_TXPDU_CANIF_IAM_CONNCANFD_Event_FrS44_CONTROLLER_0_IAM_Tx         17u
#define CANIF_TXPDU_CANIF_IAM_CONNCANFD_EvtInfo_CONTROLLER_0_IAM_Tx         18u
#define CANIF_TXPDU_CANIF_IAM_SecOC_ComKeyResp_CONTROLLER_0_IAM_Tx         19u
#define CANIF_TXPDU_CANIF_IAM_SecOC_Log_CONTROLLER_0_IAM_Tx         20u
#define CANIF_TXPDU_CANIF_IAM_ZONE_CONNCANFD_100ms_FrP56_CONTROLLER_0_IAM_Tx         21u
#define CANIF_TXPDU_CANIF_TBOX_CONNCAN_20ms_FrP02_CONTROLLER_0_IAM_Tx         22u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP49_CONTROLLER_0_IAM_Tx         23u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP55_CONTROLLER_0_IAM_Tx         24u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP58_CONTROLLER_0_IAM_Tx         25u
#define CANIF_TXPDU_CANIF_IAM_BKPCANFD_1000ms_FrP59_CONTROLLER_0_IAM_Tx         26u
#define CANIF_TXPDU_CANIF_synthesized_IAM_ZONE_CONNCANFD_E_CONTROLLER_0_IAM_Tx         27u
#define CANIF_TXPDU_CANIF_synthesized_IAM_ZONE_CONNCA_0000_CONTROLLER_0_IAM_Tx         28u
#define CANIF_TXPDU_CANIF_synthesized_IAM_ZONE_CONNCA_0001_CONTROLLER_0_IAM_Tx         29u
#define CANIF_TXPDU_CANIF_synthesized_IAM_BKPCANFD_20ms_Fr_CONTROLLER_0_IAM_Tx         30u
#define CANIF_TXPDU_CanIf_Contained_Tx_Pdu_0x36A         31u
#define CANIF_TXPDU_CanIf_Contained_Tx_Pdu_0x377         32u
#define CANIF_TXPDU_CanIf_Contained_Tx_Pdu_0x3A2         33u
#define CANIF_TXPDU_CanIf_phy_tx_0x719         34u
#define CANIF_TXPDU_CANIF_IAM_CONNCANFD_NM_IAM_NM_TxPdu         35u

#define CANIF_HRH_NUMBER           1u
#define CANIF_HOH0_HRH_0           0u

#define CANIF_HTH_NUMBER           2u
#define CANIF_HOH0_HTH_0           0u
#define CANIF_HOH0_HTH_1           1u

#define CANIF_TXBUFFER_NUMBER          2u
#define CANIF_RXBUFFER_NUMBER          0u

#define CANIF_RXNOTIFYSTATUS_BUFFER    0u
#define CANIF_TXNOTIFYSTATUS_BUFFER    0u

#define CANIF_RXINDICATION_FUNC_NUMBER     4u

#define CANIF_TXCONFIRMATION_FUNC_NUMBER     3u

#endif
/*******************************************************************************
**                      End of file                                           **
*******************************************************************************/
